### ISSUE TITLE
Concurrency Issue when injecting Lazy<T>

### ISSUE THREAD

**Issue by matthawley** [JasperFx/lamar#104]
Within our application using ASP.NET Core 2.1, we have a dependency chain that ultimately brings in Lazy<T>. The outer calls are executing asynchronously using Task.WhenAll within a single asp.net request.

When it's the first time hitting this path (_item.Value.Execute), it throws the following execption

**An item with the same key has already been added.**

```
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
at Lamar.IoC.Resolvers.ScopedResolver`1.Resolve(Scope scope)
at Lamar.IoC.Scope.GetInstance[T]()
```

I cannot get this to reproduce in a simple console test, unfortunately, but the underlying Scope uses a Dictionary which definitely isn't thread safe.

**Comment by matthawley** [comment]
Actually, this occurs whether or not we're using Lazy<T> internally.

**Comment by CodingGorilla** [comment]
I think this is related to #103 (and a couple other bugs that have come up), and in general I think @matthawley is right.  The `Scope` needs a little bit of work to make it a bit more thread safe.

**Comment by jeremydmiller** [comment]
@matthawley @CodingGorilla I'm looking at this one next. Think it'll jsut be adding locking to ScopedResolver. I had foolishly assumed that the scoped resolution would never happen in multiple threads and that code didn't have to be thread-safe. I'll first try to add a test that duplicates the exception
