### ISSUE TITLE
Error on startup in ASP.NET Core 2.1 and 2.2

### ISSUE THREAD

**Issue by EddieEt** [JasperFx/lamar#110]
Hi, thank you for making such a great library.

I apologize if this is a duplicate, but I couldn't find anything. 

The error 
```
'Open generic service type 'WebApplication2.IRepository`1[T]' requires registering an open generic implementation type.'
```
 is being thrown when I use the UseLamar extension overload to pass in a ServiceRegistry. The Registry contains one statement 

```
For(typeof(IRepository<>)).Use(typeof(SomeRepository<>));
```

Best I can tell, asp's service provider is trying to register the actual System.Type to IRepository<>.

When the registry is moved to the startup class's ConfigureContainer method the error is not thrown and everything is resolved correctly (currently this is not an option for me).

I uploaded a project reproducing the error [here](https://github.com/EddieEt/Exception-Thrown-Using-Lamar/tree/master/WebApplication2)

I'm on Windows, just upgraded to dotnet 2.2, but was seeing the error on 2.1 as well.

Please let me know if you need anymore information, thank you.

**Comment by matthawley** [comment]
I'm getting this as well using IPipelineBehavior<,> from Mediatr. The debug output after adding my type shows an instance instead of a type?

`services.For(typeof(IPipelineBehavior<,>)).Add(typeof(ApiVersionBehavior<,>));`

```
Lifetime = Singleton, ServiceType = {MediatR.IPipelineBehavior`2[TRequest,TResponse]}, ImplementationType = null
    ImplementationFactory: null
    ImplementationInstance: {new TrackOperationBehavior`2()}
    ImplementationType: null
    Lifetime: Singleton
    ServiceType: {Name = "IPipelineBehavior`2" FullName = "MediatR.IPipelineBehavior`2"}
```

**Comment by matthawley** [comment]
This seems to work fine, so it must be related to the asp.net core implementation:

```
[Fact]
public void can_add_open_generic_instance()
{
    var container = new Container(x =>
    {
        x.For(typeof(IOpenInterface<,>)).Add(typeof(OpenInterfaceImpl<,>));
    });

    var instance = container.GetInstance<IOpenInterface<string, string>>();

    instance.ShouldNotBeNull();
    instance.ShouldBeOfType<OpenInterfaceImpl<string, string>>();
}

public interface IOpenInterface<TIn, TOut>
{
}

public class OpenInterfaceImpl<TIn, TOut> : IOpenInterface<TIn, TOut>
{
}
```

**Comment by EddieEt** [comment]
I'm not sure it's in asp.net's implementation since the registration and resolution of the service works fine when moved to the ConfigureContainer function on the startup class. Can you confirm if this also works for you? Unfortunately; in my actual projects, there are some registrations I prefer to setup elsewhere.

**Comment by matthawley** [comment]
Mine pukes with the error when I do

`services.BuildServiceProvider().GetRequiredService<Something>();`

within the `ConfigureContainer`. I'm able to reproduce the scenario in a unit test. In 1.1.2, this worked when called in `ConfigureServices`.

```
[Fact]
public void use_in_app_with_open_generic_references()
{
    var builder = new WebHostBuilder();
    builder
        .UseLamar()
        .UseMetrics()
        .UseUrls("http://localhost:5002")
        .UseServer(new NulloServer())
        .UseApplicationInsights()
        .UseStartup<OpenGenericStartup>();

    using (var host = builder.Start())
    {
    }
}

public class OpenGenericStartup
{
    public void ConfigureContainer(ServiceRegistry services)
    {
        services.AddMvc();

        services.For(typeof(IOpenInterface<,>)).Add(typeof(OpenInterfaceImpl<,>));

        services.BuildServiceProvider().GetService(typeof(Container));
    }

    public void Configure(IApplicationBuilder app)
    {
        app.Run(c =>
        {
            var impl = c.RequestServices.GetService<IOpenInterface<string, string>>();
            return c.Response.WriteAsync(impl.GetType().ToString());
        });
    }

    public interface IOpenInterface<TIn, TOut>
    {
    }

    public class OpenInterfaceImpl<TIn, TOut> : IOpenInterface<TIn, TOut>
    {
    }
}
```

**Comment by jeremydmiller** [comment]
@matthawley Why would you do this code at all? `services.BuildServiceProvider().GetService(typeof(Container));` When you two get this error, is that even from a Lamar container, or is it really the built in ServiceProvider? The fact that the object is an `Instance` **is** consistent with how Lamar is supposed to work in that registration. I'm disputing in both cases whether you're actually using a Lamar container

**Comment by jeremydmiller** [comment]
@EddieEt Your issue is caused by the way that ASPNet Core actually creates a couple ServiceProvider's in the midst of bootstrapping that have Lamar specific registrations that it chokes on. I can slide around this by changing the way Lamar smuggles in `Instance` objects to `IServiceCollection`

**Comment by matthawley** [comment]
@jeremydmiller Our attempt was to manipulate specific registrations by getting other pre-registered services. I'm upgrading from 1.1.2 where that DID work when being called from `ConfigureServices`, not something that was right :) I've already started moving away from doing anything with calling `BuildServiceProvider` in `ConfigureContainer`.

**Comment by jeremydmiller** [comment]
Closing this one
