### ISSUE TITLE
License links broken in all NuGet packages

### ISSUE THREAD

**Issue by Eilon** [JasperFx/lamar#117]
For example this link: https://github.com/JasperFx/lamar/blob/master/src/Lamar/Lamar.csproj#L12

Instead of https://github.com/JasperFX/lamar/blob/master/LICENSE.txt it should be https://github.com/JasperFX/lamar/blob/master/LICENSE (no file extension).

**Comment by jeremydmiller** [comment]
@Eilon Fixed by https://github.com/JasperFx/lamar/commit/4cc6ffc3fc4629b945421ffb2106453cdab986eb. Thank you for the heads up.
