### ISSUE TITLE
Decorators in convention

### ISSUE THREAD

**Issue by dchaib** [JasperFx/lamar#120]
I have a few services that are currently registered this way:
```cs
// Service1 doesn't have a decorator with caching.
For<IService1>().Use<Service1>();
// Service2 has a decorator with caching.
For<IService2>().Use<CachedService2>()
    .Ctor<IService2>().Is<Service2>();
```

I am trying to make a convention to simplify the registration.
I used the `DefaultConventionScanner` as a starting point. I just changed it to check if there is a version of the service with cache to adjust the registration
Here is the simplified version:
```cs
public class MyConvention : IRegistrationConvention
{
    private const string CachePrefix = "Cached";

    public void ScanTypes(TypeSet types, ServiceRegistry services)
    {
        foreach (var type in types)
        {
            var @interface = type.GetInterfaces().FirstOrDefault(t => t.Name == "I" + type.Name);
            if (@interface != null)
            {
                var cachedType = types.FirstOrDefault(t => t.Name.Equals(CachePrefix + type.Name));
                if (cachedType != null && cachedType.GetInterfaces().Any(t => t.Name == "I" + type.Name))
                {
                    // There is a version with cache, register this type
                    registry.For(@interface).Use(cachedType).Ctor(@interface).Is(type);
                }
                else
                {
                    // There is no version with cache, register using the standard way
                    registry.For(@interface).Use(type);
                }
            }
        }
    }
}
```

Unfortunately, this doesn't work as there is no `Ctor` method I can use in this case (only a `Ctor<T>` version).

Is there currently a way to achieve this? If not, is this a relevant feature request?

Thanks!

**Comment by jeremydmiller** [comment]
You can work directly with `ConstructorInstance` and use its `InlineDependencies` property to add the inline dependency. When you build any `Instance`, it tracks the `ServiceType`, and that's enough for Lamar to connect the dots

**Comment by dchaib** [comment]
I have tried to do as suggested, but I think I don't understand how `InlineDependencies` are supposed to work. If that can help, I have set up a small repository to test: https://github.com/dchaib/LamarDecorator.

**Comment by jeremydmiller** [comment]
You might wanna look at IInstancePolicy in teh "Policies" page in the docs. Then you just need to add a decorator to any instance that matches your criteria

**Comment by dchaib** [comment]
I don't understand why you mentioned Policies, but this got me to the `DecoratorPolicy` and its usage of `ConstructorInstance` and I think I figured it out!

I now register the cached version like this:
```cs
registry.For(@interface).Use(cachedType)
    .AddInline(new ConstructorInstance(@interface, type, ServiceLifetime.Transient)));
```

It seems to work in my small demo, I'll try to set it up in my application tomorrow and let you know if all works well.

Thanks!

**Comment by dchaib** [comment]
All is well in the application using Lamar. I still need to translate it to StructureMap for another application, but that's another issue.

Thanks again!
