### ISSUE TITLE
Package size bloats after referencing Lamar

### ISSUE THREAD

**Issue by joostas** [JasperFx/lamar#127]
After referencing Lamar in my project and packing it I find that size of package increased hugely. (~7.5MB).
When I browsed package I see that size is bloated due to various Microsoft code analyzes dlls:
- Microsoft.CodeAnalysis.VisualBasic.dll
- Microsoft.CodeAnalysis.CSharp.dll
- Microsoft.CodeAnalysis.Workspaces.dll
- Microsoft.CodeAnalysis.dll
- ...

Maybe these analysis related dlls can be somehow removed during packing?
For example by using `PrivateAssets=all`?

**Comment by jeremydmiller** [comment]
@joostas * Microsoft.CodeAnalysis.CSharp.dll is what Lamar uses to do the runtime compilation. If you need a much smaller app size, Lamar might not be the right tool for you.

**Comment by antonioortizpola** [comment]
Could it be related to #102?
