### ISSUE TITLE
Support for passing arguments at runtime

### ISSUE THREAD

**Issue by michivogler** [JasperFx/lamar#130]
Are there any plans to add the equivilant to http://structuremap.github.io/resolving/passing-arguments-at-runtime/ ?

We're currently using the ExplicitArgument object and I can't see a away to achieve something similiar with Lamar.

**Comment by jeremydmiller** [comment]
Lamar will never support that particular feature of StructureMap (it was buggy and caused me worlds of support issues). My hope is that the eventual AutoFactory feature (which hasn't been built yet) will be a much better implementation of that general use case. And I'm sorry, but I don't have any timeframe in mind for when that would get done.

**Comment by robgha01** [comment]
Ok, to bad we cant use a ioc that wont support passing parameters if this will never be supported i guess this ioc is not what we are after R.I.P StructureMap and Lamar.

**Comment by jeremydmiller** [comment]
AutoFactory might happen, it's just not really high on my priority list for now. I don't want to support this feature because it's a huge time sink.

But, @robgha01: "I take pull requests"

**Comment by robgha01** [comment]
Okey is there anyting i could help with in that regard and how will it work ?  @jeremydmiller
