### ISSUE TITLE
Automatic Cleanup of generated Assembly

### ISSUE THREAD

**Issue by Angr1st** [JasperFx/lamar#131]
Hello ,

I am trying lamar to generate n implementations of an interface at runtime. Will these generated assemblys be disposed eventually when there is no reference to it's types or will they never disappear? Would I need to unload them manually?

**Comment by jeremydmiller** [comment]
You can't unload an assembly in .Net to the best of my knowledge.

**Comment by Angr1st** [comment]
I think with AppDomains in .net it is indeed possible to unload assemblys
If they are in a seperate AppDomain. Dotnet Core 3.0 will also have the
ability to unload assemblys. They are already testing that.
Hopefully someone will create a library in the Future creating a unified
way on all plattforms to unload assemblys.

Jeremy D. Miller <notifications@github.com> schrieb am Fr., 15. März 2019,
21:05:

**Comment by jeremydmiller** [comment]
You cannot use an AppDomain to unload an Assembly. It's possible that you could with the AssemblyLoadContext stuff in Core. Either way, you can't unload an assembly when you're still using a Type from that assembly

**Comment by Angr1st** [comment]
The generated Assembly would need to be loaded inside a separate AppDomain.
You would have to dispose of all instances of the created type before
unloading the Assembly by unloading the AppDomain.


Jeremy D. Miller <notifications@github.com> schrieb am Mo., 18. März 2019,
11:57:

**Comment by jeremydmiller** [comment]
@Angr1st That doesn't help at all. If you're generating a dynamic type, it's because you need it later.

**Comment by Angr1st** [comment]
But If I have an Infinite Number of Types that I want to generate during
the runtime of the service but I only need a limited number of them at a
time. It would be nice to be able to unload the types I dont need and
recreate when needed. For better performance I would chache a number of
them to not have to recreate them everytime.

Jeremy D. Miller <notifications@github.com> schrieb am Mo., 18. März 2019,
12:47:

**Comment by jeremydmiller** [comment]
The compilation doesn't apply to singleton scoped objects and their immediate dependencies, if that helps
