### ISSUE TITLE
Registry vs ServiceRegistry confusion

### ISSUE THREAD

**Issue by billrob** [JasperFx/lamar#133]
On https://github.com/JasperFx/lamar/blob/master/documentation/documentation/ioc/registration/registry-dsl.md

 it shows the source code using Registry in the "including-registries" samples.  I found it was supposed to be ServiceRegistry because of the note up on top.  I tried to edit the sample to fix it up for you, but see it is using the StructureMap source code and not the Lamar source.  Is there an example of linking source code samples to the Lamar source code?

**Comment by jeremydmiller** [comment]
I need to eliminate the copy of the old StructureMap testing code that's hanging out in the Lamar repository. The problem is then that's gonna break the Lamar docs left and right. Just need to rip the bandaid off
