### ISSUE TITLE
Optional Parameters in constructors

### ISSUE THREAD

**Issue by cheng93** [JasperFx/lamar#140]
https://github.com/cheng93/LamarIssue140/blob/master/LamarNullIssue/Program.cs

I've got a third party class, with optional parameters, more specifically, the values are `null`

Unfortunately Lamar doesn't provide the service when the class is instantiated.

Expected behaviour for me would be to provide the service when the value is null (not sure what to do with primitives though)

Check the link for a reproduceable issue

**Comment by jeremydmiller** [comment]
@cheng93 I can't tell what you're trying to do there. Can you do a pull request with a failing test that you think shows the wrong behavior? This is the behavior as programmed: https://github.com/JasperFx/lamar/blob/master/src/Lamar.Testing/IoC/optional_ctor_parameters.cs

**Comment by cheng93** [comment]
Here is a unit test

https://github.com/cheng93/lamar/commit/7d45bd430757148308ee155c41119315a3ee78e7

It looks like, when you have an object (`Foo`) with a constructor parameter (`logger`) with a null default, it creates the object with null.

I believe this is fine when you don't have a service registered.

However, when you do have a service registered, I would expect that service to take priority over the null value.

There is also another unit test that shows we can use inline to override the null parameter manually, but what if 
* the class (`Foo`) was internal? (this is my real life case)
* Or if there are lots of default parameters, using an inline for each of them would be a pain

**Comment by cheng93** [comment]
Closed by #141
