### ISSUE TITLE
Support for Generic Hosts

### ISSUE THREAD

**Issue by igloo15** [JasperFx/lamar#144]
ASP.Net Core is moving to use the Generic Host in the future and other types of applications beyond ASP.NET Core use Generic Hosts and Generic Host Builder. [Generic Host](https://docs.microsoft.com/en-us/aspnet/core/fundamentals/host/generic-host?view=aspnetcore-2.2).

These use a different abstraction layer called [Microsoft.Extensions.Hosting.Abstraction](https://www.nuget.org/packages/Microsoft.Extensions.Hosting.Abstractions/). The current [Lamar.Microsoft.DependencyInjection](https://www.nuget.org/packages/Lamar.Microsoft.DependencyInjection/) references the older/more specific [Microsoft.AspNetCore.Hosting.Abstractions](https://www.nuget.org/packages/Microsoft.AspNetCore.Hosting.Abstractions/) package.

This package itself references Microsoft.Extensions.Hosting.Abstraction. If you change your reference from AspNetCore to just the generic one (Extensions.Hosting.Abstractions) you would open support for Lamar to a greater range of applications. Since your not using any of the specific aspnetcore stuff in your integration you could do this without losing any integration with AspNet Core and features.

**Comment by igloo15** [comment]
While this is a good thought and I have my own internal package for supporting this it appears that Microsoft.AspNetCore.Hosting.IWebHostBuilder does not yet implement Microsoft.Extensions.Hosting.IHostBuilder. It appears to be a feature in AspNetCore 3.0 which won't be released for a couple of months. 

So despite the the nuget packages referencing each other they are not yet directly using it. Its possible the IWebHostBuilder could be cast to a IHostBuilder but it would not save us anything to totally forsake Microsoft.AspNetCore.Hosting.Abstraction yet. 

You could make a totally new package that supports just generic host and I have a fork that does just that but probably not worth it at the moment. This is definitely something to keep on the radar and add support in the future.

**Comment by jeremydmiller** [comment]
@igloo15 The AspNetCore plugin *also* has support for IHostBuilder as of Lamar.Microsoft.DependencyInjection v3.10. Honestly though, I don't see this getting properly sorted out until .Net Core 3.0 whenever that is.
