### ISSUE TITLE
Structuremap Forward equivalent? 

### ISSUE THREAD

**Issue by rekna1** [JasperFx/lamar#145]
How to return same instance for two interfaces with transient scope?

**Comment by jeremydmiller** [comment]
You're not going to make this work with transient scopes, period. You'll have to use Scoped or Singleton to pull that off in the container. You can use a Lambda registration that returns the registration for one service to the other service to mimic SM's "Forward" -- which is all the Forward() did in StructureMap anyway.

**Comment by rekna1** [comment]
Ok for me
