### ISSUE TITLE
Need Example for Console app

### ISSUE THREAD

**Issue by mchase-dev** [JasperFx/lamar#149]
I'm trying to use Lamar for a .NET Core console app, but cannot get it to work. All examples I have found are for AspNet, and the Lamar documentation provides no guidance for console apps, either. 

My main frustration is that I keep getting and error about and ambiguous constructor for Microsoft.Extensions.Logging.LoggerFactory. That might be a red herring, though, as it is probably just the first DI it tries to resolve. I suspect it's just not working at all. I was also trying to get it to work with NLog as my logging provider, but I have not made any headway on that either.

Here's what I have attempted. 

    internal static class Program
    {
        public static async Task Main(string[] args)
        {
            var builder = new HostBuilder()
                .ConfigureAppConfiguration((hostingContext, config) =>
                {
                    config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
                    config.AddJsonFile("appsettings.dev.json", optional: true, reloadOnChange: true);
                    config.AddJsonFile("appsettings.test.json", optional: true, reloadOnChange: true);
                    config.AddEnvironmentVariables();
                    if (args != null)
                    {
                        config.AddCommandLine(args);
                    }
                })
                .ConfigureLogging((hostingContext, logging) =>
                  {
                      //use NLog 
                      logging.ClearProviders();
                      logging.SetMinimumLevel(LogLevel.Trace);
                      logging.AddNLog(new NLogProviderOptions { CaptureMessageProperties = true, CaptureMessageTemplates = true });
                  })
                .ConfigureServices((hostContext, services) =>
                {
                    services.AddLamar<ServiceAssemblyRegistry>();
                    services.AddOptions();
                    services.Configure<AppSettings>(hostContext.Configuration.GetSection("AppSettings"));
                    services.AddSingleton<IHostedService, TestServiceWorker>(); //this is just a test implementation of an IHostedService
                });

            await builder.RunConsoleAsync();
        }
    }

The ServiceAssemblyRegistry looks like this:

    class ServiceAssemblyRegistry : ServiceRegistry
    {
        public ServiceAssemblyRegistry()
        {
            Scan(scanner =>
            {
                scanner.TheCallingAssembly();
                scanner.LookForRegistries();
                scanner.WithDefaultConventions();
            });
            //Policies.Add<LoggerPolicy>();
            //For<Microsoft.Extensions.Logging.ILoggerFactory>().Add(new Microsoft.Extensions.Logging.LoggerFactory());
        }
    }

The two commented out lines are my attempt to get past the ambiguous constructor error on ILoggerFactor. The Policies.Add<LoggerPolicy>(); did nothing, and adding the For<Microsoft.Extensions.Logging.ILoggerFactory>().Add(new Microsoft.Extensions.Logging.LoggerFactory()) simply introduced a new error, which was "Lamar.IoC.Instances.ObjectInstance' cannot be converted to type 'Microsoft.Extensions.Logging.ILoggerFactory". I have no idea why adding that line attempts to instatitate the ILoggerFactory as a Lamar.IoC.Instances.ObjectInstance, as I'm clearly directing it to use the LoggerFactory. I ultimately want it to use NLog, though, not the Microsoft logger, so I am probably doing something wrong in that regard as well.

Really, I just need a good working example to start with. Either my "google-fu" is lacking, or there really are no examples of Lamar in a Console app.

**Comment by Mainian** [comment]
You may have an issue with your NLog stuff, but your `services.AddLamar<ServiceAssemblyRegistry>();` uses [Lamar's optimized IOptions<T> and ILogger<T> resolution policies](https://github.com/JasperFx/lamar/blob/master/src/Lamar.Microsoft.DependencyInjection/WebHostBuilderExtensions.cs) which may be causing you issues.

For any other NLog issues, I think you can find the information you need [here](https://github.com/NLog/NLog.Extensions.Logging/issues/252).

When using the generic HostBuilder or WebHostBuilder, we need to replace the default ServiceProviderFactory with our own implementation. I know of at least two ways to do this. 

The first is what you've done, which is basically copying [Lamar's Microsoft DI for ASP.NET](https://github.com/JasperFx/lamar/blob/master/src/Lamar.Microsoft.DependencyInjection/WebHostBuilderExtensions.cs) which registers it as a singleton to the service collection. 

```
services.AddSingleton<IServiceProviderFactory<ServiceRegistry>, LamarServiceProviderFactory>();
services.AddSingleton<IServiceProviderFactory<IServiceCollection>, LamarServiceProviderFactory>();
```

Another option, when running a .NET Core console app using HostBuilder, you can provide your own ServiceProviderFactory, in this case we will use [LamarServiceProviderFactory](https://github.com/JasperFx/lamar/blob/master/src/Lamar/LamarServiceProviderFactory.cs). Obviously we could write our own factory and container, but you'll want the `CreateServiceProvider( ... )` to return something that implements IDisposable.

This is a mocked example of what worked for me when using netcoreapp2.2 and Lamar 2.0.4. 

```
.UseServiceProviderFactory<ServiceRegistry>(new LamarServiceProviderFactory())
.ConfigureContainer((HostBuilderContext context, ServiceRegistry registry) =>
{
     registry.Scan(scanner =>
     {
          //Scan stuff
     });
                    
     // Could do this in configure services 
     registry.
          .ServiceCollectionExtensionMethod(context.Configuration)
          .ServiceRegistryExtensionMethod()
          .AddHostedService<HostedThing>(); 
});
```

Also, it seems like Lamar's "Scan.WithDefaultConventions()" was changed from 2.X to 3.X. I think the 3.X is the intended behavior of this functionality, but this wasn't listed in the [changeset](https://github.com/JasperFx/lamar/releases/tag/v3.0) as a fix or change, very irritating.

**Comment by jeremydmiller** [comment]
@Mainian FWIW, Lamar's optimized IOptions/ILogger builders were junked as part of 3.0 because they were no longer necessary or valuable.

**Comment by jeremydmiller** [comment]
@mobius7777 There's a new version of the DI extension going up today that adds support for IHostBuilder

**Comment by mchase-dev** [comment]
Adding 
.UseServiceProviderFactory<ServiceRegistry>(new LamarServiceProviderFactory())
worked, thanks! 

I'm not sure what you're saying about the new 3.0 version, but I am using 3.0.1. Anyway, it is working now.

**Comment by Fniz** [comment]
Hi @mobius7777,

Could you show your example with the use of `.UseServiceProviderFactory(new LamarServiceProviderFactory())` please?

Thank You !

**Comment by mchase-dev** [comment]
@Fniz 
Basically, what I posted before. Because I am not sure exactly what part of the example you might want, here's the whole CreateHostBuilder method, using the LamarServiceProviderFactory:

```
private static IHostBuilder CreateHostBuilder(string[] args)
{
	var builder = new HostBuilder()
		.ConfigureAppConfiguration((hostingContext, config) =>
		{
			config.AddJsonFile("appsettings.json", optional: false, reloadOnChange: true);
		})
		.UseServiceProviderFactory<ServiceRegistry>(new LamarServiceProviderFactory())
		.ConfigureServices((hostContext, services) =>
		{
			services.AddLamar<ServiceAssemblyRegistry>(); //my project's ServiceAssemblyRegistry for Lamar
			services.AddOptions();
			services.AddHostedService<SomeHostedService>();
		})
		.UseConsoleLifetime();

	return builder;
}

```

**Comment by Fniz** [comment]
Thank you I will try
