### ISSUE TITLE
Using Lamar with Microsoft Hosting/DependencyInjection is returning too many instances.

### ISSUE THREAD

**Issue by hellfirehd** [JasperFx/lamar#152]
Basically, I'm trying to use Lamar for it's type scanning and registries while still relying on Microsoft's DI framework.  In particular, I want `ConnectImplementationsToTypesClosing(typeof(IHandleMessages<>))`.

However, once the host is built and the `ServiceProvider` is returned, `ServiceProvider.GetServices<IHandleMessages<FooMessage>>()` gives me back two instances when there should only be one, and four when there should be two.

This [gist](https://gist.github.com/hellfirehd/23e65bd8c66cb32fbbff5e6b12163856) demonstrates it perfectly.

Can anyone tell me what I'm doing wrong?  (I mean, besides using Microsoft.Extensions.DependencyInjection instead of just pure Lamar. 😛)

**Comment by CodingGorilla** [comment]
This one is funny, I just spent two hours debugging this and realized the solutions is really simple.  Comment out your `.ConfigureContainer()` in the failing test and run it again. 😄 

You're creating a new container against an existing `ServiceRegistry`, the new container runs the scan a **second** time, adding all the registrations to the existing `ServiceRegistry` **again**.

**Comment by hellfirehd** [comment]
D'oh!  Thank you so much!
