### ISSUE TITLE
"Reset" Lamar Singletons Instances

### ISSUE THREAD

**Issue by mrxrsd** [JasperFx/lamar#161]
Hi,

Is it possible to "reset" Lamar singletons instances? 

I'm trying to generate code on-the-fly and inject as singleton instances. But I want to be capable of make changes on the generated code and inject the new version without reset my host.

**Comment by jeremydmiller** [comment]
Not right now, no. You can take advantage of the `Injectable` feature I suppose. I really didn't want to support that kind of thing in Lamar because of the complexity and/or perf hit that caused in StructureMap.
