### ISSUE TITLE
Support of .Net Core 3.0 for Lamar.Microsoft.DependencyInjection

### ISSUE THREAD

**Issue by vhatsura** [JasperFx/lamar#187]
I used `Lamar.Microsoft.DependencyInjection` from .net core 3.0 preview7 (this is possible because `3.0.0` is higher than `3.0.0-previewX`) and it works perfectly without any issues. I believe the upper bound can be update to include 3.0
https://github.com/JasperFx/lamar/blob/24127a21d0729ec15d48ff02d8998b69d93668c1/src/Lamar.Microsoft.DependencyInjection/Lamar.Microsoft.DependencyInjection.csproj#L23-L25

**Comment by tjrobinson** [comment]
This should now be resolved.

* https://jeremydmiller.com/2019/09/26/lamar-and-oakton-join-the-net-core-3-0-party/
* https://www.nuget.org/packages/Lamar.Microsoft.DependencyInjection/4.0.0
