### ISSUE TITLE
Strong name signing for the assembly

### ISSUE THREAD

**Issue by stefandascalu64** [JasperFx/lamar#194]
I am using Lamar in a project that has a strong name key and the fact that this binary is not signed is causing some problems when I try to publish.
Are there any plans to add this in the future so I can use nuget.org binaries instead of my current annoying workaround?

**Comment by jeremydmiller** [comment]
Lamar is very purposely **not** signed and will not likely be in the future.

Have you tried StrongNamer as a workaround?

**Comment by stefandascalu64** [comment]
yes, but after some issues we ended up giving up on the whole mess.
Can you tell me the reason why it is "very purposely not signed"

**Comment by stefandascalu64** [comment]
yes, but after some issues we ended up giving up on the whole mess.
Can you tell me the reason why it is "very purposely not signed"

**Comment by jeremydmiller** [comment]
Strong naming causes a whole lot of pain downstream, especially for libs like Lamar that will be diamond dependencies. This isn't a new discussion by any stretch of the imagination.
