### ISSUE TITLE
Core 3.0 logging callout

### ISSUE THREAD

**Issue by randyridge** [JasperFx/lamar#195]
Ran into an issue with logging not being properly filtered, was going to create a repro, but found
workaround in your unit test linked below (note from 2017).  I'm happy to PR documentation for a callout about it, but before I do is there a reasonable workaround for .UseLamar()?  Seems like I would not easily fall into a pit of success here...

[Code with note of workaround](https://github.com/JasperFx/lamar/blob/a58a2c652301bd726583c15976fbfac42557bb06/src/LamarWithAspNetCore3/integrating_with_HostBuilder.cs#L57)

**Comment by jeremydmiller** [comment]
I think I'd prefer to just have this done automatically in the call to UseLamar(). I'm in the code right now, I'll do it.
