### ISSUE TITLE
TheCallingAssembly throw exception on french computer

### ISSUE THREAD

**Issue by Maxime-Deharbonnier** [JasperFx/lamar#196]
There is a bug when i tried to use this method TheCallingAssembly on french computer because in CallingAssembly.Find(); the application get the stacktrace (in my case in french).
The stacktrace in french looks like : 
`   à System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)`
and in english :
`   at System.Web.Hosting.PipelineRuntime.InitializeApplication(IntPtr appContext)`
The bug append here:
`        private static Assembly findAssembly(string stacktraceLine)
        {
            var candidate = stacktraceLine.Trim().Substring(3); // Works only for english version
`

**Comment by jeremydmiller** [comment]
Fixed by #197
