### ISSUE TITLE
Lifecycle management

### ISSUE THREAD

**Issue by andygithub** [JasperFx/lamar#21]
Do you have any plans for the types of lifecycle that Lamar would be supporting?  Are you planning to bring all of the SM ones to Lamar or will there be a subset?

**Comment by jeremydmiller** [comment]
@andygithub See the section on object lifecycles here: https://jeremydmiller.com/2018/02/26/differences-between-bluemilk-and-structuremap/.

Long story short, it's using the `ServiceLifetime` enumeration and semantics from ASP.Net Core that's somewhat different than StructureMap. For the sake of keeping things simpler and faster, I wasn't planning on supporting anything else or any kind of pluggable scoping like SM had.

**Comment by andygithub** [comment]
Ok, thanks
