### ISSUE TITLE
Core 3.0 logging filters #195

### ISSUE THREAD

**Issue by ralmlopez** [JasperFx/lamar#211]
I had the same issue with logging filters as issue #195. I had to manually add the code in my Program.cs file for log filtering to work. I am using Lamar 4.0.

`                .ConfigureServices((context, services) =>
                {
                    services.AddSingleton<ILoggerFactory, LoggerFactory>(sp =>
                        new LoggerFactory(
                            sp.GetRequiredService<IEnumerable<ILoggerProvider>>(),
                            sp.GetRequiredService<IOptionsMonitor<LoggerFilterOptions>>()
                        )
                    );
                }) 
`

**Comment by jeremydmiller** [comment]
@ralmlopez I think this is still the same issue as #195, I haven't gotten that one out to Nuget yet.

**Comment by ralmlopez** [comment]
You are right. I thought that it had already made it into the nuget package, my mistake. Thanks. Loving the new library.

**Comment by jeremydmiller** [comment]
Duplicate, closing this.
