### ISSUE TITLE
Version Numbers

### ISSUE THREAD

**Issue by MikeWilliams-UK** [JasperFx/lamar#214]
The version numbers for this project are confusing.

On NuGet Gallery https://www.nuget.org/packages/Lamar/ it is at 4.0.0
In releases here in GitHub https://github.com/JasperFx/lamar/releases it is at 3.0.4
On the documentation site https://jasperfx.github.io/lamar/documentation/ it is at 3.1.0

Can you please get them all in sync

**Comment by jeremydmiller** [comment]
@MikeWilliams-UK Are you volunteering to help? All this bookkeeping takes time, and I don't have a huge amount of bandwidth for this kind of thing.

**Comment by jeremydmiller** [comment]
Done.

**Comment by MikeWilliams-UK** [comment]
Many thanks
