### ISSUE TITLE
Feature request: BuildUp method

### ISSUE THREAD

**Issue by kutensky** [JasperFx/lamar#217]
Currently, there's no way to set all properties of already initialized object as it was in StructureMap with method "BuildUp".
That creates problems with transition from StructureMap to Lamar. 
As a use case, BuildUp needed to use DependencyInjection on Action Filter Attributes in MVC.

**Comment by jeremydmiller** [comment]
@kutensky Sounds like a great pull request.

**Comment by jeremydmiller** [comment]
Closed for now by #219, but needs an optimization later
