### ISSUE TITLE
Microsoft.Extensions.DependencyInjection.Abstractions dependency version range

### ISSUE THREAD

**Issue by bbbush** [JasperFx/lamar#236]
Hi-

Just want to report that some packages cannot install due to version conflict. The 3.x package of Microsoft.Extensions.DependencyInjection.Abstractions was released a while ago https://www.nuget.org/packages/Microsoft.Extensions.DependencyInjection.Abstractions/3.0.0 and Lamar has a dependency version range of 2.0+

One of such package is Microsoft.Extensions.Logging.Debug 3.1.2

Thanks!

**Comment by kevindqc** [comment]
Had the same issue and found this in `Lamar.csproj`:

```
<ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.0' ">
    <PackageReference Include="System.Runtime.Loader" Version="4.3.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="[2.0.0, 3.0.0)" />
  </ItemGroup>

  <ItemGroup Condition=" '$(TargetFramework)' == 'netstandard2.1' ">
    <PackageReference Include="System.Runtime.Loader" Version="4.3.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="[3.0.0, 4.0.0)" />
  </ItemGroup>
```

Not sure why I need to use `netstandard2.1` for this but switching to it works. Hopefully I don't need my DLLs in a .NET Framework project in the future! lol

**Comment by bbbush** [comment]
I get it. There is no issue with Lamar then.

Thanks!
