### ISSUE TITLE
Decorators and generics

### ISSUE THREAD

**Issue by danspam** [JasperFx/lamar#24]
Is it possible to do the following yet. Or is there some other way to achieve this?

For(typeof(IFoo<,>)).DecorateAllWith(typeof(Bar<,>));

**Comment by jeremydmiller** [comment]
Yes and no. It's not terribly obvious, but the *hook* is there to make it happen w/ a custom decorator policy, but I don't have the open generic version of a policy pre-built and usable from the fluent interface. It's not a crazy amount of work if you're comfortable enough w/ open generic type gymnastics if you wanna do the pull request for it;)

**Comment by danspam** [comment]
Not sure I will ever be _comfortable_ with open generic gymnastics, as I don't have to deal with it in detail that often but I will take a look and see if I can figure out what is needed.

**Comment by jeremydmiller** [comment]
If you do, look at `IDecoratorPolicy`, and the simple implementation of that for closed types. There's a `Type.Closes(openGenericType)` extension method in the codebase that should help you test for whether the policy should apply (left over from StructureMap)

**Comment by danspam** [comment]
Thanks for this.. I did try to figure out what was needed but could not get my head around what needed to be done
