### ISSUE TITLE
is there a replacement for HttpContextLifecycle in Lamar

### ISSUE THREAD

**Issue by minoseah629** [JasperFx/lamar#241]
this class existed in structuremap.  

is there a plan to bring it in?

[HttpContextLifecycle](https://github.com/structuremap/structuremap/blob/5f811f63c1afbd0e63ae653c8d33fd3c3fefc444/Source/StructureMap/Pipeline/HttpContextLifecycle.cs)

**Comment by jeremydmiller** [comment]
You don't need it in ASP.Net Core because you effectively get that for free with the `Scoped()` lifecycle. Same if you're using a nested container per request in ASP.Net MVC v5 or Web API

But no, I don't intend to bring that back.
