### ISSUE TITLE
Support for `IAsyncDisposable`

### ISSUE THREAD

**Issue by kieronlanning** [JasperFx/lamar#243]
Add support for `IAsyncDisposable` to enable disposable operations that require asynchronous execution, in the same way that `IDisposable` is currently supported.

Initially, this could be an ASP.NET Core integration only due to the async nature of the request pipeline.

**Comment by jeremydmiller** [comment]
I might try to get into this over the holidays

**Comment by kieronlanning** [comment]
Thanks @jeremydmiller!
