### ISSUE TITLE
Documentation "Building objects with Lambdas"

### ISSUE THREAD

**Issue by jasase** [JasperFx/lamar#255]
I try the example from the documentation [Building objects with Lambdas](https://jasperfx.github.io/lamar/documentation/ioc/lambdas/) but it is not working. 

After changing the code I got the basic example running. But i need the function `Expression<Func<IContext, T>> builder` to upgrade from StructureMap. But it is not available

**Comment by jeremydmiller** [comment]
@jasase That's some very old StructureMap syntax that has gotten incorrectly copied over in the docs. You do have the ability to expose Lambda registrations that use either IServiceContext that effectively exposes the container. You don't have all the contextual information that you did in StructureMap, and that's actually on purpose. Lamar won't support everything that's on structureMap's `IContext`
