### ISSUE TITLE
Runtime compilation failure due to protection level

### ISSUE THREAD

**Issue by HamsterExAstris** [JasperFx/lamar#26]
I've got a new ASP.NET Core application where I'm trying to use Lamar (v0.9.4), and having some issues. Just to make sure it (probably) isn't my code, I changed to StructureMap and that worked just fine, so this seems to be Lamar-specific.

`CS0122: 'AuthenticationBuilder.EnsureSignInScheme<TOptions>' is inaccessible due to its protection level`

```
public override Microsoft.Extensions.Options.IPostConfigureOptions<Microsoft.AspNetCore.Authentication.Facebook.FacebookOptions> Build(Lamar.IoC.Scope scope)
{
     return new Microsoft.AspNetCore.Authentication.AuthenticationBuilder.EnsureSignInScheme<Microsoft.AspNetCore.Authentication.Facebook.FacebookOptions>(_options_of_AuthenticationOptions);
}
```

I can give you a complete solution if you want it, but you should be able to replicate it with the MVC starter template by adding Facebook authentication in `ConfigureServices()`:

```
services.AddAuthentication().AddFacebook(facebookOptions =>
            {
                facebookOptions.AppId = Configuration["Authentication:Facebook:AppId"];
                facebookOptions.AppSecret = Configuration["Authentication:Facebook:AppSecret"];
            });
```

**Comment by jeremydmiller** [comment]
@HamsterExAstris I'll get to this one soon. I thought we had all this kind of thing addressed w/ the IdentityServer, but here we go.

**Comment by jeremydmiller** [comment]
@HamsterExAstris Sorry, but this one is "works on my box". This is what I did:

```
        public void ConfigureContainer(ServiceRegistry services)
        {
            services.AddMvc();
            services.AddLogging();
            services.AddIdentityServer()
                .AddDeveloperSigningCredential()
                .AddInMemoryApiResources(Config.GetApiResources())
                .AddInMemoryClients(Config.GetClients());
            services.For<IMessageMaker>().Use(new MessageMaker("Hey there."));
            
            
            services.AddAuthentication().AddFacebook(facebookOptions =>
            {
                facebookOptions.AppId = "something";
                facebookOptions.AppSecret = "else";
            });
            
        }
```

and every registration in the service collection could be built.

Anything else you've got in your registration that might be making this blow up in combination?

**Comment by jeremydmiller** [comment]
No updates, so I'm closing this one.
