### ISSUE TITLE
Why is transient lifetime applied to the inner instance when decorators are applied ?

### ISSUE THREAD

**Issue by paziz001** [JasperFx/lamar#262]
I am using a custom decorator policy and I've noticed that the lifetime of the instance I am trying to decorate always changes to transient.
This happens when the decorators are applied here.
https://github.com/JasperFx/lamar/blob/master/src/Lamar/ServiceFamily.cs#L76

**Comment by jeremydmiller** [comment]
@paziz001 I honestly don't remember exactly why I had to do that, but I'd guess that it was to make the dependency be completely inlined to the decorator. You're effectively the lifecycle of the decorator instance at that point.

Does this actually matter?

**Comment by paziz001** [comment]
I had an issue with some scoped instances that would be decorated and then would change to transient.
But the actual issue was somewhere else actually so you can close this.
Thanks :)

**Comment by jeremydmiller** [comment]
Gotcha.
