### ISSUE TITLE
netstandard2.1 support 

### ISSUE THREAD

**Issue by ransht** [JasperFx/lamar#296]
I'm upgrading to NET5
and I have issues with Lamar.Microsoft.DependencyInjection v 6.0.0
its not compatible with net standard2.1
so now should I change all standard2.1 to NET5 because 4.3.0 is not supported in NET5
or is there going to be release for standard2.1 ?

**Comment by jeremydmiller** [comment]
I'm starting work on a .Net 6 able release right now. Within a day or two, or right after Thanksgiving at worst.
