### ISSUE TITLE
.Net 6 Support

### ISSUE THREAD

**Issue by wendellestradairely** [JasperFx/lamar#298]
Got this warning on .NET 6:

warning NU1608: Detected package version outside of dependency constraint: Lamar 6.0.0 requires Microsoft.Extensions.DependencyInjection.Abstractions (>= 5.0.0 && < 5.9.0) but version Microsoft.Extensions.DependencyInjection.Abstractions 6.0.0-rc.2.21480.5 was resolved.

**Comment by Zwergenpunk** [comment]
Now that .net 6 is released, it would help alot while upgrading projects to have this fixed.

**Comment by christianfredh** [comment]
Having some dependency issues in out project. One other 3rd party library are requiring Microsoft.Extensions.Hosting.Abstractions 6.0.0 but Lamar.Microsoft.DependencyInjection 6.0.0 (which is the latest currently) does only support Microsoft.Extensions.Hosting.Abstractions (>= 3.0.0 && < 5.9.0).

It would be great to have this fixed!

**Comment by christianfredh** [comment]
PR: https://github.com/JasperFx/lamar/pull/300

**Comment by gamoreli** [comment]
> PR: #300

any updates about this guys?

**Comment by robi26** [comment]
Yeah, would be really nice to have an update soon, as we use Lamar as a core package in our libraries.

**Comment by marcos-prins** [comment]
hello, any updates about this guys?

**Comment by Zwergenpunk** [comment]
Jeremy said on gitter that he is planning on releasing a new version early in the current week. I guess it will be released soon.

**Comment by marcos-prins** [comment]
> Jasper said on gitter that he is planning on releasing a new version early in the current week. I guess it will be released soon.

great! thanks for the info

**Comment by thisispaulsmith** [comment]
Any ETA on this? Thanks

**Comment by jeremydmiller** [comment]
https://jeremydmiller.com/2021/11/29/jasperfx-oss-plans-for-v6-marten-et-al/

TL:DR This week.
