### ISSUE TITLE
Lamar tagging is confusing

### ISSUE THREAD

**Issue by tmc101** [JasperFx/lamar#322]
Hi

What version is Lamar currently at?

I've just grabbed the source code and looked at the tags on the master branch:

![image](https://user-images.githubusercontent.com/11647741/151592837-216fe280-b3d5-43c7-a8f8-96c3719656bf.png)

As far as I can tell the guide (https://jasperfx.github.io/lamar/guide/) doesn't say which version it applies to.

It does link to the release notes here:

https://github.com/JasperFx/lamar/releases

Which show the latest release as v4.3 from Apr 20, 2020 :

Where can I find information about the latest release and any bug fixes or breaking changes?

**Comment by jeremydmiller** [comment]
master is 7.1.1. All Nuget releases are done from master.

https://jeremydmiller.com/2021/12/01/lamar-v7-meets-net-6-minimal-apis-and-iasyncdisposable/
https://jeremydmiller.com/2021/08/23/lamar-v6-is-out-expanded-interception-options-overriding-test-services-better-documentation/

**Comment by tmc101** [comment]
Thanks - blog bookmarked.
