### ISSUE TITLE
Document: Microsoft DI Specification compliance 

### ISSUE THREAD

**Issue by maulik-modi** [JasperFx/lamar#325]
DisposesInReverseOrderOfCreation and ResolvesMixedOpenClosedGenericsAsEnumerable tests are mentioned as skipped:
https://github.com/dotnet/runtime/blob/main/src/libraries/Microsoft.Extensions.DependencyInjection/tests/DI.External.Tests/Lamar.cs

**Comment by jeremydmiller** [comment]
Yes, and very unlikely to ever be addressed.
