### ISSUE TITLE
Using .AddHttpClient(..) in a child-ServiceRegistry results in logging added twice

### ISSUE THREAD

**Issue by dougbenham** [JasperFx/lamar#326]
```
var registry = new Registry();
registry.AddLogging();
registry.IncludeRegistry<OtherRegistry>();
```

```
class OtherRegistry : ServiceRegistry
{
   public OtherRegistry()
   {
      this.AddHttpClient(...);
   }
}
```

Registrations around logging end up getting messed up because many things are added twice. Is there a workaround for this?

**Comment by dougbenham** [comment]
I could just make some extension method like this instead:

```
static class OtherRegistryExtensions 
{
   public static ServiceRegistry AddOther(this ServiceRegistry services)
   {
      services.AddHttpClient(...);
      return services;
   }
}
```

But then we aren't using the child ServiceRegistry logic anymore and instead are just continuing to work with the primary ServiceRegistry. What are the benefits of using child ServiceRegistries?

**Comment by jeremydmiller** [comment]
@dougbenham How is logging getting added twice? Is AddHttpClient() quietly doing a second AddLogging() somehow? I'm not following exactly why this would be a Lamar error.

**Comment by dougbenham** [comment]
> @dougbenham How is logging getting added twice? Is AddHttpClient() quietly doing a second AddLogging() somehow? I'm not following exactly why this would be a Lamar error.

Yes you can see the source here:
![image](https://user-images.githubusercontent.com/5466350/153082827-7e400918-9f48-4f6a-b660-d6e9c070b1eb.png)

And then in Lamar, you can see how it just naively appends all of the registrations:
![image](https://user-images.githubusercontent.com/5466350/153083080-16a5ffef-df83-4a27-b496-dc8a6f84285d.png)

This results in logging being added twice. Anyways I don't see a way around this, it just kinda ruins the `.IncludeRegistry(..)` methods for any practical purposes. Forced to work with the primary service registry at all times so that you don't encounter weird issues like this.

**Comment by jeremydmiller** [comment]
Okay. There's nothing that's really actionable here, so I'm closing the issue. Just don't call the AddHttpClient() from an additional Lamar ServiceRegistry is all I can say here.
