### ISSUE TITLE
Remove `Console.WriteLine` calls

### ISSUE THREAD

**Issue by Rob89** [JasperFx/lamar#335]
I've just updated to Marten v5 (kudos for getting that out) and I now get a lot of logging like this:

```
Generated code for EventStore.PeriodProjectionRuntimeSupport1412857744
...
```

E.g. introduced here:
https://github.com/JasperFx/lamar/commit/75200465ce8d15f1e7224dacecd7b9872b193f41#diff-8fe5bf83ca4f3444dd61ef6569ff56643febb0d0dc5ab4fe6ce6777265fe47c5R18

It's a minor annoyance as the logging can't be disabled using the normal log levels configuration.

Thanks for all the great work.

**Comment by jeremydmiller** [comment]
The latest code generation uses ILogger now, and those messages are Debug level.
