### ISSUE TITLE
Can lamar be used with the older full framework ASP.NET WebAPI?

### ISSUE THREAD

**Issue by lorenh** [JasperFx/lamar#337]
I only see examples for .NET Core.  I think I know the answer is probably no, but I wanted to confirm.  Unity is being deprecated and I'm shopping for a replacement DI container to replace it in an old legacy service we cannot port to .NET Core yet.  Autofac was recommended, but I thought I'd give lamar a look too.

**Comment by jeremydmiller** [comment]
Yes. PITA because it was always a bolt on with Web API, but yes. Easiest thing to do is find the old StructureMap adapter for Web API, then pretty well find & replace "StructureMap" with "Lamar". I'd **love** to ditch netstandard2.0 support, but we need that for work, so it's still there.
