### ISSUE TITLE
What is the current release version of Lamar?

### ISSUE THREAD

**Issue by OwenPattison** [JasperFx/lamar#338]
I'm trying to understand what the current version of Lamar actually is since getting a dependabot upgrade from 4.3.1 to 8.0.1
![image](https://user-images.githubusercontent.com/5864244/166705695-113593b4-95df-4d37-b79e-007a5426822f.png)

In the releases, it shows 4.3 as current: https://github.com/JasperFx/lamar/releases

But then tags do go up to: 6.1.4: https://github.com/JasperFx/lamar/tags

Really I'm just looking for some clarity on this thank you.

**Comment by jeremydmiller** [comment]
The latest is 8.0.1.

Nuget.org is always the authoritative resource: https://www.nuget.org/packages/Lamar/

**Comment by hisuwh** [comment]
Do you track release notes somewhere else.  Jump from 4.3 to 8 suggests 4 lots of breaking changes - need to understand the details of what these are before we can upgrade?

**Comment by jeremydmiller** [comment]
@hisuwh Dude, you really need to understand that this *Free* OSS project that I mostly support all by myself has very little resources for the kind of tracking you seem to be wanting here. I mostly use GitHub issue milestones to track major work. 

In the case of Lamar, the major version upgrades generally mean dropping .Net versions or dealing with changes to WebHostBuilder/HostBuilder model changes as I rev the main library and the ASP.Net Core adapters all together. 

Lamar itself has been very stable in its original behavior and API. I can't think of any major or even minor issue you'll have moving to newer versions.

**Comment by hisuwh** [comment]
Yh I appreciate that and I appreciate your effort on this.  But equally pushing tags and release notes is part of the OSS lifecycle.  Github can even do it for you when you create a release:
![image](https://user-images.githubusercontent.com/4470351/168863626-b2d5acb7-0e83-4680-9612-75dae23eaa12.png)

Bumping the major version implies a potential breaking change, and as a consumer of your OSS package I want to understand what that is so I can appropriately mitigate the risk.

**Comment by jeremydmiller** [comment]
@hisuwh I'm aware of that, but that takes time. I need you to immediately go away and leave me alone, unless you're volunteering to do all the bookkeeping here. I do not owe you one damn thing.

**Comment by hisuwh** [comment]
Sorry if I have come across as critical here.  That was not my intent.  
I merely wanted to understand what has changed between versions.  However, if this is difficult to work out and/or you do not have the capacity to identify this I totally understand.

As I say I appreciate your efforts on this.  I think this is an inspired and elegant solution to DI extending the built-in capability.   It has enabled me to quickly build a robust production application - I simply want to ensure this continues to stay this way.
