### ISSUE TITLE
Resolving (seemingly) bi-directional dependency blows up on SOE

### ISSUE THREAD

**Issue by jokokko** [JasperFx/lamar#35]
To repro:
```
public interface If { }

public class N : If
{
	public N(IEnumerable<If> n)
	{
	}
}

var container = new Container(x =>
{
	x.For<N>().Use(ctx => new N(Enumerable.Empty<If>()));

	x.For<If>().Use<N>();
});

var instance = container.GetInstance<If>();
```

blows up on SOE. On fixing this, is warning about bi-directional dependency desired or should N be constructed as defined in the expression? How about default policy on constructing such IEnumerable ctor args by omitting types that are of the same as the type being constructed?

Obviously SOE should not happen... Can be worked around by configuring explicit LambdaInstance for constructing `If` or `IEnumerable<If>`. I believe StructureMap's `Forward` was also a way to work around this problem.

**Comment by jeremydmiller** [comment]
@jokokko It should warn by throwing an exception. The `N` is getting created by Lamar finding all known registrations for `If`, which would get itself. There *should* already be some bi-directional dependency detection that catches in this case that's obviously not working here.

I think right now I'd rather have the bi-directional detection actually work here as the first step. I know there have been folks occasionally wanting to have StructureMap support composite patterns where you'd really need it to filter out the composite registration in the "all possible".

I can play with this one a little bit tonight or tomorrow maybe.

**Comment by jeremydmiller** [comment]
Fixed the detection, but we'll still need to do something else for handling composites like this. Hopefully SM would have thrown the bi-directional dependency warning, but it couldn't handle that case either.
