### ISSUE TITLE
Large dependency graphs can cause StackOverflowException

### ISSUE THREAD

**Issue by bryanboettcher** [JasperFx/lamar#361]
We encountered an instance where Lamar would begin to throw StackOverflowExceptions while debugging integration tests.  These tests are a bit sloppy and will double-register some implementations, telling us we were very near a threshold of overflow.  The exceptions stemmed from both `EnumerableExtensions.Visit`, as well as the `IResolverFrame` system.

Replacing the clean recursive code with more manual iterative code using a Stack object will help mitigate this.

**Comment by jeremydmiller** [comment]
Closed by #362
