### ISSUE TITLE
`IServiceProviderIsService` not returning `true` for various registrations

### ISSUE THREAD

**Issue by andrewlock** [JasperFx/lamar#368]
I was just playing using Lamar with minimal APIs and I've found there are various cases where injected services aren't being inferred because Lamar's `IServiceProviderIsService` implementation isn't return `true` for various cases:

- `IEnumerable<T>` where multiple `T` registered
- `IGenericService<T>` open generic
- `ConcreteClass` when not explicitly registered

Sample app demonstrating the issue below. Note that in all cases, add `[FromServices]` fixes the issue - it's not the registration at issue, it's the call to `IServiceProviderIsService` that's wrong. This repros on .NET 6 and .NET 7, giving the following error (indicating none of the args were resolved from DI)

```bash
InvalidOperationException: Body was inferred but the method does not allow inferred body parameters.
Below is the list of parameters that we found:

Parameter | Source
---------------------------------------------------------------------------------
services  | Body (Inferred)
concrete  | UNKNOWN
generic   | UNKNOWN

```

I haven't done an extensive search for all the cases that are/aren't found, but these seem to be the main culprits

Thanks!

```csharp
using Lamar;
using Lamar.Microsoft.DependencyInjection;

var builder = WebApplication.CreateBuilder(args);
builder.Host.UseLamar(services =>
{
    services.Scan(s =>
    {
        s.AssemblyContainingType(typeof(Program));
        s.WithDefaultConventions();
        s.AddAllTypesOf<IService>();
    });
});

var app = builder.Build();

app.MapGet("/", (IEnumerable<IService> services,
    ConcreteClass concrete,
    IGenericService<ConcreteClass> generic) => "Hello World!");

app.Run();

public interface IService { }
public class ServiceA : IService { }
public class ServiceB : IService { }

public class ConcreteClass {}

public interface IGenericService<T> {}
public class GenericService<T> {}
```

**Comment by jeremydmiller** [comment]
Ugh, @andrewlock I didn't realize that was part of their "spec" for how that was supposed to work. Okay. This is one of those times when I curse the conforming container behavior that's rammed down our throats

**Comment by andrewlock** [comment]
> Ugh, @andrewlock I didn't realize that was part of their "spec" for how that was supposed to work. Okay. 

To be totally fair, I'm not _entirely_ sure that it definitely is, but best I understand the expectations of `IServiceProviderIsService` it's "if you can resolve the type from the container, it should return `true`". 

> This is one of those times when I curse the conforming container behavior that's rammed down our throats

😬 yeah, I totally get that. The fact there's no real spec for it doesn't help either 🙄

**Comment by dadhi** [comment]
I was thinking that MS.DI Spec tests should catch all cases :/ Now upping to .Net 7 means more work :(

**Comment by andrewlock** [comment]
> I was thinking that MS.DI Spec tests should catch all cases :/ Now upping to .Net 7 means more work :(

Just to be clear, this is "broken" in .NET 6 too, so not technically tied to the .NET 7 upgrade..

**Comment by jeremydmiller** [comment]
Think this will be in a new Lamar 10.0 soon.
