### ISSUE TITLE
Adding migrations when using EF Core hangs

### ISSUE THREAD

**Issue by CodingGorilla** [JasperFx/lamar#38]
I am trying to create the migrations using the VS package managemer console's `add-migration` cmdlet as described here: https://docs.microsoft.com/en-us/ef/core/get-started/aspnetcore/new-db .  With Lamar as my IoC container the cmdlet just hangs after writing out what looks like is some debugging info like:

```
[12:54:41 VRB] All Scanners
================================================================
```

No other output, and the only solution is to close visual studio and restart it.

**Comment by jeremydmiller** [comment]
Is it doing any kind of file scanning to discover assembly files maybe? If it works after restarting VS, that smells like a file locking problem to me. Definitely something we could harden Lamar against

**Comment by CodingGorilla** [comment]
So it does not work after restarting visual studio, but the package manager console is hung until you restart visual studio (sorry that wasn't clear).  

It has to find the `DbContext` and some other types in order to set up the migrations.  Based on the output I was seeing, I was guessing that it is attempting to use the DI system to discover the types.  But it's not clear that's the case.  

Using the dotnet cli I can get it to create the migrations without any problems, so this might be a tooling problem in VS that is not related to Lamar.  This is fine for my use case (using the CLI), so unless you're concerned about this, then it's probably safe to close the issue.

**Comment by jeremydmiller** [comment]
I don't have another answer other than file locking. Could try to harden the file scanning against that, but that's just shooting in the dark right now. I vote to close this.
