### ISSUE TITLE
provide licence information via nuget package

### ISSUE THREAD

**Issue by DMDTT** [JasperFx/lamar#384]
Hey there, 
it would be nice to expose the licence type, etc. within the nuget package information.

Background:
then it could be used togther with  dotnet-project-licenses tool https://github.com/tomchavakis/nuget-license

**Comment by DMDTT** [comment]
<img width="964" alt="image" src="https://github.com/JasperFx/lamar/assets/4932585/4cfed404-75ab-415c-917c-9c11c7995b57">

see screen., the space between version and licence url could be the licence type

**Comment by jeremydmiller** [comment]
I take pull requests.
