### ISSUE TITLE
Add support for .NET 8 keyed services

### ISSUE THREAD

**Issue by Simble** [JasperFx/lamar#388]
The .NET DI container now has support for keyed services. See: https://weblogs.asp.net/ricardoperes/net-8-dependency-injection-changes-keyed-services

However, Lamar's ServiceRegistry does not implement the new/required interface methods yet and therefore when trying to use a keyed service, you will run in to run time error of System.InvalidOperationException with message "This service descriptor is keyed. Your service provider may not support keyed services."

**Comment by rizi** [comment]
@jeremydmiller can we use the current version of lamar as long as we don't use keyed services in .net 8/aspnet.core 8 or does lamar needed to be extended? I want to upgrade to .net 8/aspnet.core 8 when it gets released (14. november)

Br

**Comment by jbogard** [comment]
plz fix your library it's blocking MediatR from releasing

**Comment by rizi** [comment]
> plz fix your library it's blocking MediatR from releasing

@jbogard I'm curious, do you use KeyedServices explicitly or why isn't the current version of Lamar working (as long as you use "named registrations" instead of KeyedServices)

Br

**Comment by jbogard** [comment]
The package explicitly excludes 8.0 in its version ranges

**Comment by lt-nvos** [comment]
Lamar currently indeed restricts updating a project to .NET 8.0:

`Lamar.Microsoft.DependencyInjection 12.0.1 -> Microsoft.Extensions.Options (>= 6.0.0 && < 8.0.0)`

An update would be greatly appreciated.

**Comment by jeremydmiller** [comment]
> @jeremydmiller can we use the current version of lamar as long as we don't use keyed services in .net 8/aspnet.core 8 or does lamar needed to be extended? I want to upgrade to .net 8/aspnet.core 8 when it gets released (14. november)
> 
> Br

To the best of my knowledge, yes

**Comment by jeremydmiller** [comment]
Folks, .NET 8 went GA **yesterday**. A little patience please.

**Comment by jeremydmiller** [comment]
> https://weblogs.asp.net/ricardoperes/net-8-dependency-injection-changes-keyed-services

@Simble For the record, StructureMap/Lamar supported "keyed services" literally 20 years ago. But yes, I was already going to work on this support today for the .NET conforming container adapter.

**Comment by Simble** [comment]
@jeremydmiller, I'm aware of that, and been using it for years! Thanks for making it happen
