### ISSUE TITLE
Explicit Container.Release() method

### ISSUE THREAD

**Issue by jeremydmiller** [JasperFx/lamar#41]
Boo! Always hated this in Windsor back in the day, but being compliant with what the ASP.Net overlords say we have to do requires it.

**Comment by jeremydmiller** [comment]
Hell no, never going to do this. To hell with them.

**Comment by davidfowl** [comment]
What is this? Dispose on IServiceScope?

**Comment by jeremydmiller** [comment]
@davidfowl Nah, this was old Windsor-style, explicit "Container.Release(object)" mechanics. If you're not familiar with that, it was instant memory leaks for the unwary. For some reason I thought at one point this was going to be required for AspNetCore compliance.

**Comment by davidfowl** [comment]
Got it.
