### ISSUE TITLE
Overriding registry entry for certain interfaces

### ISSUE THREAD

**Issue by dmcconnell86** [JasperFx/lamar#43]
Hi,

Im not sure if I am missing this in the documentation anywhere but does Lamar support overriding how to resolve an instance by declaring it again later in the registry list?

We are currently migrating over from structuremap to Lamar and we currently scan an assembly then do any specific overrides. For example in structure map we would scan an assembly then do specific overrides for certain interfaces:

```
 var container = new Container(x =>
            {
                x.Scan(scan =>
                {
                    scan.AssemblyContainingType<IUnitOfWork>(); //get entire assembly dependancies    
                scan.WithDefaultConventions();               
                });
                x.For<IUnitOfWork>().Use(() => new UnitOfWork()); //override specific class
                
            });
```

In lamar, when I try this, I can see there is a second registry entry created and the latter does not get chosen. In the example below, the default registry is used, not the registry with the mocked out Unit of work.
```
 var x = new ServiceRegistry();

            x.Scan(scan =>
            {
                scan.AssemblyContainingType<IUnitOfWork>(); //get Carrier Integration
                scan.WithDefaultConventions();
            });

            //use a mocked out Unit of work instead of the real one in tests.
            x.For<IUnitOfWork>().Use(c => MockUow.Object);
```

Is there any way to do a scan then override particular interfaces with specific implementations? Do I need to somehow remove the scanned instance before I attempt to 'override' the interface?

**Comment by jeremydmiller** [comment]
Sigh. Right now it's all order dependent like the ASP.Net Core DI container or Autofac. The discovered registrations through the scanning are appended to the end of the registrations and I think that's the source of your problems here. 

I guess the answer is should we try to maintain the exact order as is implied by the order of operations in that ServiceRegistry? I didn't do that upfront because that just made things more complicated. 

I'm in a bit of a hurry to make it to 1.0, so maybe speak up now if you can;-)

**Comment by dmcconnell86** [comment]
Thanks Jeremy,

I believe the order is important, especially in a testing scenario. For example, we scan a projects assembly at the start of the test so that we can use IOC to create the class that we want to test. Alot of our code has several nested dependancies which some should run in the test, whilst others should be mocked. Previously in structure map we scan the whole assembly then mock out the specific 'dangerous' dependencies.
