### ISSUE TITLE
StructureMap LookForRegistries equivalent?

### ISSUE THREAD

**Issue by ghost** [JasperFx/lamar#45]
Hello,

I think I can't find the LookForRegistries equivalent in Lamar?

[SM doc](http://structuremap.github.io/registration/auto-registration-and-conventions/)

Can you point me to some alternatives?

Regards,
Cezary

**Comment by jeremydmiller** [comment]
That would be because I'm literally working on adding that to Lamar this very minute;)

https://github.com/JasperFx/lamar/issues/5
