### ISSUE TITLE
When resolving a handler from a HTTP request exception with message Unable to cast object of type 'Lamar.IoC.Scope' to type 'Lamar.IContainer'. is thrown

### ISSUE THREAD

**Issue by MrKevHunter** [JasperFx/lamar#47]
When trying to resolve a handler in a controller from a api request i get the message

`Unable to cast object of type 'Lamar.IoC.Scope' to type 'Lamar.IContainer'.`

This appears to be due to the registration written
```
this.For<ITableConnection>()
                .Use<TableConnection>().Ctor<string>().Is(c => c.GetInstance<IConfiguration>()["Storage:PrimaryConnectionString"]);
```

If I hard code the returned string the class resolves properly the `TableConnection` class takes a single string property

**Comment by jeremydmiller** [comment]
It was specific to being used within the ASP.Net Core service scope abstractions, which I had of course never thought to test this particular permutation of things. Fix is coming in v1.0.1 shortly.
