### ISSUE TITLE
Compilation failure when using IdentityServer4.AccessTokenValidation (optional parameters)

### ISSUE THREAD

**Issue by JathanMoline** [JasperFx/lamar#48]
Any input or direction in solving would be appreciated.   This is currently a blocker for a rather large migration from structuremap to lamar.  

some references since the Microsoft namespace is used in the projects directly: 
https://github.com/IdentityServer/IdentityServer4.AccessTokenValidation/blob/29ed50c5b5950e7dde5efdce81dea4c774d20db0/src/IdentityServer4.AccessTokenValidation/IdentityServerAuthenticationExtensions.cs

https://github.com/IdentityModel/IdentityModel.AspNetCore.OAuth2Introspection/blob/94b0ccb4d5723b3992c05bf229cb1c476f280c3a/src/IdentityModel.AspNetCore.OAuth2Introspection/OAuth2IntrospectionOptions.cs

Message: System.InvalidOperationException : Compilation failures!

CS1746: The delegate 'Func<IDistributedCache, IPostConfigureOptions<OAuth2IntrospectionOptions>>' does not have a parameter named 'cache'

```
 // START: Microsoft_Extensions_Options_IPostConfigureOptions_Microsoft_AspNetCore_Builder_OAuth2IntrospectionOptions__postConfigureOAuth2IntrospectionOptions
    public class Microsoft_Extensions_Options_IPostConfigureOptions_Microsoft_AspNetCore_Builder_OAuth2IntrospectionOptions__postConfigureOAuth2IntrospectionOptions : Lamar.IoC.Resolvers.SingletonResolver<object>
    {
        private readonly IDistributedCache _distributedCache;
        private readonly Func<Microsoft.Extensions.Caching.Distributed.IDistributedCache, Microsoft.Extensions.Options.IPostConfigureOptions<Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions>> _func_of_IDistributedCache_IPostConfigureOptions_Microsoft_AspNetCore_Builder_OAuth2IntrospectionOptions_;
        private readonly Scope _topLevelScope;

        public Microsoft_Extensions_Options_IPostConfigureOptions_Microsoft_AspNetCore_Builder_OAuth2IntrospectionOptions__postConfigureOAuth2IntrospectionOptions(IDistributedCache distributedCache, Func<Microsoft.Extensions.Caching.Distributed.IDistributedCache, Microsoft.Extensions.Options.IPostConfigureOptions<Microsoft.AspNetCore.Builder.OAuth2IntrospectionOptions>> func_of_IDistributedCache_IPostConfigureOptions_Microsoft_AspNetCore_Builder_OAuth2IntrospectionOptions_, Scope topLevelScope) : base(topLevelScope)
        {
            _distributedCache = distributedCache;
            _func_of_IDistributedCache_IPostConfigureOptions_Microsoft_AspNetCore_Builder_OAuth2IntrospectionOptions_ = func_of_IDistributedCache_IPostConfigureOptions_Microsoft_AspNetCore_Builder_OAuth2IntrospectionOptions_;
            _topLevelScope = topLevelScope;
        }



        public override object Build(Lamar.IoC.Scope scope)
        {
            return _func_of_IDistributedCache_IPostConfigureOptions_Microsoft_AspNetCore_Builder_OAuth2IntrospectionOptions_(cache: _distributedCache);
        }

    }

    // END: Microsoft_Extensions_Options_IPostConfigureOptions_Microsoft_AspNetCore_Builder_OAuth2IntrospectionOptions__postConfigureOAuth2IntrospectionOptions
```
	
#### How to replicate:  

In Lamar.AspNetCoreTests 

1. Install IdentityServer4.AccessTokenValidation 2.6.0
2. In integration_with_aspnetcore.cs-ConfigureContainer line 174 Change to
```    
services.AddAuthentication()
            .AddIdentityServerAuthentication(options =>
            {
                options.Authority = "auth";
                options.RequireHttpsMetadata = true;
            });
```
Run Test:  use_in_app

#### How to eliminate error message (temporary workaround): 			
Able to get things to compile by editing OptionalArgumentVariable.Usage to remove the parameter name.    I went as far as to remove the parameter name when there was only one matching constructor in ContructorInstance.DetermineConstructor.

Changed ``` return $"{_parameter.Name}: {_inner.Usage}"; ``` to ``` return _inner.Usage; ```

**Comment by jeremydmiller** [comment]
@JathanMoline Your fix is what it *should* be doing anyway. I'm trying to add your configuration to the existing ASP.Net Core + IdentityServer smoke tests to see if I can get a failing test first, then I'll make that change

**Comment by jeremydmiller** [comment]
Got the failing test, but that workaround would break other things. I'm working on a different fix now.

**Comment by jeremydmiller** [comment]
Got it, it'll be in Lamar 1.0.2 in a bit
