### ISSUE TITLE
NestedContainer affects parent container

### ISSUE THREAD

**Issue by danielpalme** [JasperFx/lamar#49]
If you override a type registration in a child container, this also affects the parent container:

```
using System;
using Lamar;
using Microsoft.Extensions.DependencyInjection;

namespace LamarTest
{
    public class Program
    {
        static void Main(string[] args)
        {
            var registry = new ServiceRegistry();
            registry.AddTransient<IService, DefaultService>();
            var container = new Container(registry);
            Resolve<DefaultService>(container);

            var nestedContainer = container.GetNestedContainer();
            nestedContainer.Configure(c => c.AddTransient<IService, NestedService>());
            Resolve<NestedService>(nestedContainer);

            // Wrong service is resolved from parent container
            Resolve<DefaultService>(container);
        }

        private static void Resolve<ExpectedType>(IContainer container)
        {
            var service = container.GetRequiredService<IService>();

            if (service is ExpectedType)
            {
                Console.WriteLine($"Expected type '{typeof(ExpectedType)}' was resolved");
            }
            else
            {
                Console.WriteLine($"Failure. Resolved '{service}' instead of '{typeof(ExpectedType)}'");
            }
        }
    }

    public interface IService
    {
    }

    public class DefaultService : IService
    {
    }

    public class NestedService : IService
    {
    }
}
```

**Comment by jeremydmiller** [comment]
There is a workaround you can use here that's meant for this kind of thing: https://jasperfx.github.io/lamar/documentation/ioc/injecting-at-runtime/

Lamar is never going to support adhoc overrides of services in the nested containers. `Configure()` was only put on the container interface as a workaround to ASP.Net Core and the way it keeps trying to create extra containers at bootstrapping time. The fact that it was accessible was a mistake on my part in the rush to get this thing out.

The *fix* is going to have the nested container throw an exception if you try to call Configure() on it, or to use a different interface for the nested container to hide that.

**Comment by danielpalme** [comment]
Thanks for the explanation. You can close this issue if you like.

**Comment by jeremydmiller** [comment]
@danielpalme It's a very real usability issue. This signature will be quietly removed in 1.1 as I shamelessly flaunt strict semver compliance.
