### ISSUE TITLE
Debugging dynamically generated and loaded assembly

### ISSUE THREAD

**Issue by stiano** [JasperFx/lamar#50]
Is there a way to debug the generated assembly from VS17? I am trying to execute the end_to_end_compilation.generate_dynamic_types_with_no_fields, generator.Generate(3, 4). 

I have tried to extend LoadFromStream method with symbols as well, but with no success.

internal interface ILamarAssemblyLoadContext
{
	Assembly LoadFromStream(Stream assembly, Stream symbols);
	Assembly LoadFromAssemblyName(AssemblyName assemblyName);
	Assembly LoadFromAssemblyPath(string assemblyName);
}

**Comment by dominikjeske** [comment]
I have the same problem with my own code compiled with Roslyn - https://stackoverflow.com/questions/50649795/how-to-debug-dll-generated-from-roslyn-compilation

**Comment by stiano** [comment]
I have solved the mystery. Check out the answer on stackoverflow. https://stackoverflow.com/questions/50649795/how-to-debug-dll-generated-from-roslyn-compilation/51955400#51955400

**Comment by jeremydmiller** [comment]
@stiano Cool! Can I talk you into a PR for that into Lamar?

**Comment by jeremydmiller** [comment]
Moot point now, removing this altogether from Lamar
