### ISSUE TITLE
Ambigious reference between IHostingEnvironment

### ISSUE THREAD

**Issue by vhatsura** [JasperFx/lamar#51]
When I try to use Lamar library with [App.Metrics.AspNetCore.Mvc library](https://www.nuget.org/packages/App.Metrics.AspNetCore.Mvc/3.0.0-alpha-0094) in ASP.Net Core 2.1 application I got the following exception:

```
System.InvalidOperationException: Compilation failures!

CS0104: 'IHostingEnvironment' is an ambiguous reference between 'Microsoft.AspNetCore.Hosting.IHostingEnvironment' and 'Microsoft.Extensions.Hosting.IHostingEnvironment'
CS0104: 'IApplicationLifetime' is an ambiguous reference between 'Microsoft.AspNetCore.Hosting.IApplicationLifetime' and 'Microsoft.Extensions.Hosting.IApplicationLifetime'
```
The code which is configured application:
```CSharp
public class Program
{
    public static void Main(string[] args)
    {
        CreateWebHostBuilder(args).Build().Run();
    }

    public static IWebHostBuilder CreateWebHostBuilder(string[] args) =>
        WebHost.CreateDefaultBuilder(args)
            .UseLamar()
            .UseMetrics()
            .UseStartup<Startup>();
}
```

Archive with solution to reproduce issue:
[InvalidOperationExceptionOnStart.zip](https://github.com/JasperFx/lamar/files/2112694/InvalidOperationExceptionOnStart.zip)

**Comment by jeremydmiller** [comment]
@vhatsura,

I'm guessing that you've got mixed ASP.Net Core 2.0 and 2.1 in your codebase?

I'm going to make this a de facto default in Lamar v1.1, but the temporary workaround is to use this flag in bootstrapping:

```
            var container = new Container(x =>
            {
                x.Policies.DynamicAssemblySharing = DynamicAssemblySharing.Individual;
            });
```

**Comment by vhatsura** [comment]
@jeremydmiller.

Thanks for suggestion. It works.
