### ISSUE TITLE
Compilation error when using the RazorEngine package

### ISSUE THREAD

**Issue by danspam** [JasperFx/lamar#54]
I am using RazorEngine https://github.com/Antaris/RazorEngine and if I try to use lamar with this then you get a compilation error when the asp.net site starts (CS0118: 'RazorEngine' is a namespace but is used like a type). 

I guess the issue is related to #51 in the fact that the lack of explicit namespaces in the generated code is causing conflicts. 

A failing unit test is here: https://github.com/danspam/lamar/tree/razorengine-issue

 I will try to see if I can figure out a fix for this and add a PR, although if this is the same type of issue as #51 then perhaps a more extensive fix in the code generation is needed that will cover other similar cases?

**Comment by danspam** [comment]
Well, it looks like PR #52 will fix my failing test too. I guess I should have checked that first...

**Comment by jeremydmiller** [comment]
@danspam Can you try Lamar 1.0.3 and see if it addressed this issue?

**Comment by danspam** [comment]
Yes, that has fixed the issue. Thanks. 👍
