### ISSUE TITLE
Injectable to accept Open Generics

### ISSUE THREAD

**Issue by wooderz** [JasperFx/lamar#55]
Thanks for adding the Injectable system. The idea is sound, however I think it needs to accept open generics. MassTransit for example has both a `ConsumerContext` and a `ConsumerContext<T>`

I think we'd need to make Injectable allow the open type `ConsumerContext<>` and then be able to `_.Inject(context)` which may be a `ConsumerContext<SomeClass>` etc etc

This would need to be implemented using a Type object rather than Generic method I suppose?

`serviceRegistry.Injectable(typeof(ConsumerContext<>))`

I've had a look at implementing myself, but think I'd need to chat it through as I do it. So really am making this ticket as a reminder for either myself to attach it once I can get some gitter help, or if Jeremy knows the right way to implement this already?

**Comment by jeremydmiller** [comment]
This was closed by activity in MassTransit. I'm closing this.
