### ISSUE TITLE
Can I inititialize WebHostBuilder with and existing container?

### ISSUE THREAD

**Issue by RubenDelange** [JasperFx/lamar#61]
Cfr. this thread for Structuremap integration in ASP.NET Core with an existing container : https://github.com/structuremap/StructureMap.Microsoft.DependencyInjection/issues/23

Is this possible with Lamar?

**Comment by jeremydmiller** [comment]
Not yet, honestly hadn't thought about it is all. Feel like doing a PR for that?

**Comment by jeremydmiller** [comment]
Yeah, after thinking this through more, I really don't want to have to support this with Lamar because it opens up the post Container construction `Configure()` issues.

**Comment by vdesmedt** [comment]
So what would be the approach if we need to share the container between a console app and a WebApi in .Net Core (both hosted in the same process of course) ?

**Comment by jeremydmiller** [comment]
@vdesmedt You'd be using `IHost` and `IHostBuilder` to bootstrap both the web app and the console app right? It's `IHost.Services` regardless. That's pretty well in the box in .Net Core.

**Comment by vdesmedt** [comment]
I did not knew about IHost & Console App but indeed it makes it very easy & clean !  Thanks
