### ISSUE TITLE
NullReferenceException in NpgsqlCompositeMethodCallTranslator.cs with Lamar 1.0.3

### ISSUE THREAD

**Issue by CodingGorilla** [JasperFx/lamar#62]
After switching to ASP.Net 2.1 and EF Core 2.1, I'm now getting an NRE when starting up my project related to initializing the Npgsql EF provider.  This appears to be happening because Lamar is injecting a "default" (read: empty) instance of the `INpgsqlOptions` into the `NpgsqlCompositeMethodCallTranslator` constructor.

This is related to: https://github.com/npgsql/Npgsql.EntityFrameworkCore.PostgreSQL/issues/494

This appears to be an issue with Lamar not providing the proper instance, but I'm still trying to track down where and how the proper instance would be registered.

**Comment by jeremydmiller** [comment]
@CodingGorilla So, no clue without more information. Can you do a DescribePlan() on the thing that isn't being built correctly and see what you can see? And what version of this is Lamar? We did have a bug post 1.0 for optional constructor arguments that might be tripping this off

**Comment by CodingGorilla** [comment]
I plan to do some more troubleshooting tomorrow, the problem I'm having is that the exception happens before the call to `Startup.Configure`, it happens _right after_ `Startup.ConfigureServices` and in my initial troubleshooting I couldn't get a reference to an `IContainer` to use any of Lamar's troubleshooting tools.

I was a bit confused because I expected the `IServiceCollection` passed into `Startup.ConfigureServices` to be a container of some sort, but I guess not?

**Comment by CodingGorilla** [comment]
@jeremydmiller What instance do I run DescribePlan() on?  So far all I've been able to determine is that the container has a Singleton registered using the default constructor for `NpgsqlOptions`.  I'm still trying to track down where the actual registration should be happening though.

**Comment by CodingGorilla** [comment]
@jeremydmiller Ok, I pulled the latest source and built against that and the problem seems to go away.  I can't tell you what exactly solved the problem, but it seemed to be an order of construction issue.  Lamar seemed to want to build the `NpgsqlCompositeMethodCallTranslator` before entity framework itself had started up and run the initialization on all of the `ISingletonOptions`.

Without the debug build of 1.0.3 I couldn't figure out why, and like I said switching to the latest code seems to have solved it.  Maybe you have an idea?

**Comment by jeremydmiller** [comment]
My guess is that somewhere there's a constructor that has a parameter with a default value. More or less, code that wasn't designed for being used within an IoC tool but is.

**Comment by CodingGorilla** [comment]
If that's the case, then what would have changed in your latest code (1.1.0) that would have solved that problem?  Also, any timeline for 1.1.0?
