### ISSUE TITLE
Compilation failure in 1.1

### ISSUE THREAD

**Issue by danspam** [JasperFx/lamar#64]
After updating to 1.1, I get a compilation failure when attempting to use the ComponentSpace.Saml2 library:

`CS1503: Argument 1: cannot convert from 'Microsoft.Extensions.Options.IOptions<ComponentSpace.Saml2.Session.DistributedSsoSessionStoreOptions>' to 'Microsoft.Extensions.Options.IOptionsSnapshot<ComponentSpace.Saml2.Session.DistributedSsoSessionStoreOptions>'`

This did not occur in 1.0.x

See https://github.com/danspam/lamar/tree/saml-issue for failing test.

**Comment by jeremydmiller** [comment]
@danspam Hey, could I get you to make a PR for that failing test?

I put in an optimization for IOption<T> into 1.1 that's apparently breaking your particular use case. Not sure where, how, or why yet.

**Comment by danspam** [comment]
No problem - PR #65  .  Note that ComponentSpace.Saml2 is a timed trial of a commercial product. As such it would definitely be better to create a more targeted test once the problem has been identified, so that the dependency on ComponentSpace.Saml2 can be removed.

**Comment by jeremydmiller** [comment]
@danspam Hey, thanks for your help with this one. The fix is in Lamar.Microsoft.DependencyInjection v1.1.1. Might take a bit for Nuget to index it though.
