### ISSUE TITLE
The ConfigureServices method must either be parameterless or take only one parameter of type IServiceCollection.'

### ISSUE THREAD

**Issue by dhjgodin** [JasperFx/lamar#67]
I've followed the documentation but get "'The ConfigureServices method must either be parameterless or take only one parameter of type IServiceCollection."

I have the following:

    public class Program
    {
        public static void Main(string[] args)
        {
            var builder = new WebHostBuilder();
            builder
                // Replaces the built in DI container
                // with Lamar
                .UseLamar()

                // Normal ASP.Net Core bootstrapping
                .UseKestrel()
                .UseStartup<Startup>();

            builder.Start();
        }
    }

and 

    public class Startup
    {
        public void ConfigureServices(ServiceRegistry services)
        { ...`

If I change it to IServiceCollection, services is of type Microsoft.Extensions.DependencyInjection.ServiceCollection not ServiceRegistry 

I'm using .net Core 2.1.1

**Comment by chuckconway** [comment]
I've encountered the same error, I am also using Core 2.1.1.

I spend a few hours trying to workaround this issue, but I wasn't able to access Lamar outside of passing it in as a parameter. 

When .UseLamar is called, and IServiceCollection is passed into the ConfigureServices method Lamer does intercept the DI calls, but without access to Lamar's instance, there isn't any advantage in using it.

I've used STructureMap for years. I love it. The scanning features are the bomb. I'm looking forward to using Lamar.

**Comment by mike-echo-oscar-whiskey** [comment]
```
    public class Program
    {
        public static void Main(string[] args)
        {
            BuildWebHost(args).Run();
        }

        public static IWebHost BuildWebHost(string[] args)
        {
            var registry = new ServiceRegistry();

            registry.Scan(s =>
            {
                s.TheCallingAssembly();
                s.WithDefaultConventions();
            });

            return WebHost.CreateDefaultBuilder(args)
                .UseLamar(registry)
                .UseStartup<Startup>()
                .Build();
        }
    }
```

**Comment by jeremydmiller** [comment]
Hey everyone, until I get time to delve into whatever changed in ASP.Net Core v2.1 and adjust Lamar to work through the Startup mechanism, the workaround (really just an alternative) is what @youfoundkris posted above.

@chuckconway @dhjgodin ^^^^^

**Comment by chuckconway** [comment]
Awesome! Works for me!

**Comment by dhjgodin** [comment]
Fixed for me too, cheers for the work arround

**Comment by arishlabroo** [comment]
ConfigureServices takes IServiceCollection, but ConfigureContainer takes whatever container you have added to your webhostbuilder. Below works in startup class

```
public class Startup
{
    public void ConfigureContainer(ServiceRegistry services)
    { ...`
```

**Comment by jeremydmiller** [comment]
Made the docs reflect this and published.
