### ISSUE TITLE
Unable to cast object of type 'Lamar.IoC.Scope' to type 'Lamar.IContainer'. exception when injecting IContainer in a constructor in an ASP.NET Core 2.1 app

### ISSUE THREAD

**Issue by seanjmalone** [JasperFx/lamar#76]
I reluctantly need to inject the container into a class in an ASP.NET Core 2.1 web app. When doing so I get the exception message:

`Unable to cast object of type 'Lamar.IoC.Scope' to type 'Lamar.IContainer'.`

I'm using version 1.1.1, so I don't believe it's the same as issue #47.

The simplest way I can find to reproduce the problem is:

1. Create a new ASP.NET Core 2.1 MVC web app
2. Add the Lamar.Microsoft.DependencyInjection v1.1.1 NuGet package
3. Add .UseLamar() to program.cs
4. Update ConfigureServices(IServiceCollection services) to ConfigureContainer(ServiceRegistry services)
5. Add a constructor to the HomeController.cs like:

```C#
public class HomeController : Controller
{
    private readonly IContainer _container;

    public HomeController(IContainer container)
    {
        _container = container;
    }

    // Other stuff...
}
```
6. Start debugging

If I try getting an instance of the HomeController outside of an HTTP request IContainer is injected fine:

```C#
public void ConfigureContainer(ServiceRegistry services)
{
    // Other stuff...
    
    var container = new Container(services);
    var homeController = container.GetInstance<HomeController>();
}
```
So I'm not sure if this is a bug or some configuration that I'm missing.

**Comment by CodingGorilla** [comment]
I've run into this before as well, not sure what @jeremydmiller 's position on it is (whether it's a bug or by design).  But as a work around, what I did was inject `IServiceProvider` and then cast it to `IContainer`.

**Comment by seanjmalone** [comment]
Thanks @CodingGorilla,  injecting `IServiceProvider` gave me something I could breakpoint and investigate:

```C#
private readonly IContainer _container;
private readonly Scope _scope;

// Exception injecting IContainer
public QueryProcessor(IContainer container)
{
    _container = container;
}

// Exception casting IServiceProvider to IContainer
public QueryProcessor(IServiceProvider serviceProvider)
{
    _container = (IContainer)serviceProvider;
}

// Exception injecting Scope
public QueryProcessor(Scope scope)
{
    _scope = scope;
}

// Doesn't cause any exceptions
public QueryProcessor(IServiceProvider serviceProvider)
{
    _scope = (Scope)serviceProvider;
}
```

The bottom constructor allows me to access `_scope.GetInstance();`, but I could definitely do with finding out the recommended approach.

**Comment by CodingGorilla** [comment]
It's interesting to me that you get an exception on your second constructor (casting to `IContainer`).  I currently use some code that's similar to this, and "it works for me"(tm).

**Comment by seanjmalone** [comment]
Yeah I thought the same. I've just tried it again, I get:

```C#
public QueryProcessor(IServiceProvider serviceProvider)
{
    // System.InvalidCastException: Unable to cast object of type 'Lamar.IoC.Scope' to type 'Lamar.IContainer'.
    _container = (IContainer)serviceProvider;
}
```

**Comment by jeremydmiller** [comment]
What version are you using? I thought we'd fixed this. Can you try injecting `IServiceContext` instead?

**Comment by seanjmalone** [comment]
It's version Lamar.Microsoft.DependencyInjection version 1.1.1. When I try injecting `IServiceContext` I get an exception saying `...IServiceContext is not registered within this container and cannot be auto discovered by any missing family policy`.

**Comment by jeremydmiller** [comment]
Do you mind raising a bug for this in GH? At best it needs some documentation.

**Comment by CodingGorilla** [comment]
@seanjmalone Oh, you're probably in a nested container, I think I did this using the root container.  Lamar has always seemed a little weird to me how those interfaces are set up, and I think coming from StructureMap is a bit confusing.  You sort of expect `INestedContainer` to inherit from `IContainer`, or `Scope` to inherit from `Container`, but it doesn't.  It's probably easiest to just inject the `Scope` directly.

**Comment by seanjmalone** [comment]
@jeremydmiller Is there another place for bugs? I'm only familiar with the Issues bit. I guess I could put a solution up in GitHub if it helps.

@CodingGorilla I'm on day 2 with Lamar coming from Simple Injector, so if I'm using a nested container, it definitely wasn't on purpose!

**Comment by jeremydmiller** [comment]
"Is there another place for bugs?" -- duh, Jeremy, I already raised the issue.

Here's fine, I just wasn't thinking that we were already talking here;)

SimpleInjector might have had another name for what I call "nested containers". ASPNet Core calls them scopes, AutoFac calls them "Lifecycle" and so on. It happens automatically if you're using ASP.Net Core behind the scenes on a per HTTP request basis.

**Comment by seanjmalone** [comment]
Just to follow up on this. The object I'm injecting into is registered as scoped, and is being used during an HTTP request, so I guess this means I'm resolving it from a nested container. I'm not sure if this explains only being able to inject an `IServiceProvider`, and not say a `Scope`- according to `container.WhatDoIHave()` they both seem to be available:

```
===============================================================================================================================================================================================================================================================================
ServiceType                                                                     Namespace                                                               Lifecycle     Description                                                                     Name                     
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
IServiceProvider                                                                System                                                                  Scoped        Current IServiceProvider                                                        IServiceProvider         
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Scope                                                                           Lamar.IoC                                                               Scoped        Current Scope                                                                   Scope                    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
```

But as far as I can tell casting `IServiceProvider` to `Scope` so I can access `_scope.GetInstance()` is working consistently so the issue could be closed.

**Comment by jeremydmiller** [comment]
@seanjmalone @CodingGorilla Just so you know, I'm gonna beat this by making you use the `IServiceContext` interface, but also have it blow up if you try `IContainer` with a message to use `IServiceContext` instead. It's a breaking change from SM behavior, but it only exposes service location methods and I think that's more appropriate anyway

There'll be related doc changes too.

**Comment by jeremydmiller** [comment]
@seanjmalone @CodingGorilla This "works on my box" in the master code. What version of Lamar were you using? Either way, I'd rather have folks use IServiceContext so nobody tries to do silly things like change the registrations at runtime from that.

**Comment by seanjmalone** [comment]
@jeremydmiller The test project I was using only referenced `Lamar.Microsoft.DependencyInjection` v1.1.1. This has a >= 1.1.0 dependency on `Lamar`, so although I was using the latest version of `Lamar.Microsoft.DependencyInjection` I wasn't using the latest version of `Lamar` (v1.1.1). I'm going to explicitly reference `Lamar` are re-test...

**Comment by seanjmalone** [comment]
Ok, so I don't see any difference between v1.1.0 and v1.1.1, my findings are the same as my 2nd post.

The only way I can get service location to work in a scoped object is:

```C#
public class Test : ITest
{
    private readonly Scope _scope;

    public Test(IServiceProvider serviceProvider)
    {
        _scope = (Scope)serviceProvider;
        var something = _scope.GetInstance<Something>();
    }
}
```
Injecting `IContainer`, `Scope` & `IServiceContext` all fail. My guess is that `IContainer` maybe shouldn't work with it being scoped and I don't really know what `IServiceContext` is, but `Scope` looks like there might be a genuine bug:

According to the exception the generated code uses the same variable name twice here:
`var scope = (Lamar.IoC.Scope) scope;`

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Compilation failures!

CS0136: A local or parameter named 'scope' cannot be declared in this scope because that name is used in an enclosing local scope to define a local or parameter
CS0841: Cannot use local variable 'scope' before it is declared
CS0165: Use of unassigned local variable 'scope'

Code:

using System.Threading.Tasks;

namespace Jasper.Generated
{
    // START: WebApplication1_ITest_test
    public class WebApplication1_ITest_test : Lamar.IoC.Resolvers.ScopedResolver<WebApplication1.ITest>
    {


        public override WebApplication1.ITest Build(Lamar.IoC.Scope scope)
        {
            var scope = (Lamar.IoC.Scope) scope;
            return new WebApplication1.Test(scope);
        }

    }

    // END: WebApplication1_ITest_test
    
    
}


  Source=Lamar
  StackTrace:
   at Lamar.Compilation.AssemblyGenerator.Generate(String code)
```
This was caused by:
```C#
public class Test : ITest
{
    private readonly Scope _scope;

    public Test(Scope s)
    {
        _scope = s;
    }
}
```
Perhaps this is irrelevant if `IServiceContext` is going to be the approach going forwards, I just need to find out how to get at it.

**Comment by CodingGorilla** [comment]
Yea, I can see how trying to inject a `Scope` will throw an exception; Lamar actually generates code and compiles it, and this generated assembly is your "injector".  The generated code always consumes a `Scope` as it's constructor parameter, so attempting to inject _another_ scope will naively just create another local variable called `scope` as you can see.  This is probably a bug that should be fixed (maybe I'll work on a PR for this).

I do think there needs to be some documentation as to what the function of each of the different containers are _intended_ to be used for.  But `IServiceContext` is available on `Container` which inherits from `Scope` where it is primarily implemented.  I _believe_ that `Container` is used as the "root" of the injection system, e.g. you set up a container to bootstrap Lamar.  A scope seems to be a subset of the container (since the `Container` inherits from it, obviously) that seems to be used internally for the actual code generation.  I'm not sure that scope is intended to be used directly?

If you're using ASP.NET Core, then _I think_ the recommended approach should be to use [System.IServiceProvider](https://docs.microsoft.com/en-us/dotnet/api/system.iserviceprovider?redirectedfrom=MSDN&view=netcore-2.1).  This is the root of Microsoft's dependency injection system, and indeed `IServiceContext` inherits from this interface.  This has the benefit of allowing you to "swap out" lamar for Microsoft's DI system if you ever needed to (or some other system that is compliant with Microsoft's DI system) while still giving you access to Lamar's functionality.

That's my penny and a half.. :smile:

**Comment by seanjmalone** [comment]
Thanks @CodingGorilla.

> I do think there needs to be some documentation as to what the function of each of the different containers are intended to be used for.

I've definitely been guessing a bit.
