### ISSUE TITLE
Setter injection

### ISSUE THREAD

**Issue by xorets** [JasperFx/lamar#79]
What's up with setter injection? It's mentioned in the docs, but it seems to be not implemented at all.

**Comment by ardalis** [comment]
I saw a blog post saying "PRs welcome" for this feature, but that's all I've heard. Where is it discussed in the docs?

**Comment by xorets** [comment]
@ardalis , hmm, I think I referred this page: https://jasperfx.github.io/lamar/documentation/ioc/registration/inline-dependencies/. Some time already passed since that moment, so I don't remember exactly.

**Comment by jeremydmiller** [comment]
Necessary test cases:

- [x] Quick build
- [ ] Inline dependencies
