### ISSUE TITLE
aspnet core Startup configuration being ignored with decorators

### ISSUE THREAD

**Issue by arishlabroo** [JasperFx/lamar#83]
Not really sure if this problem is limited to decorators, but if I register a decorator in my ConfigureContainer method of the startup class, it is not being registered. Exact same test for structuremap works fine. Also if I use the same registration in a console application with Lamar, it works fine too. 
Feels like the problem is when lamar is trying to replace the built in service provider interfaces from aspnet core. Not able to track where. 

https://github.com/JasperFx/lamar/pull/82
This pull request with a small test shows the issue. (closed the PR since it was just to highlight the issue)

**Comment by arishlabroo** [comment]
The problem seems like it is limited to IOptionsFactory<> .

https://github.com/JasperFx/lamar/blob/master/src/Lamar.Microsoft.DependencyInjection/OptionsInstance.cs#L87
as you can see, `OptionsPolicy` manually news up a concrete optionsfactory, ignoring any decorators.

I am trying to achieve this FYI
https://github.com/aspnet/Home/issues/2752

**Comment by arishlabroo** [comment]
:( I guess the same issue applies to our loggers too
https://github.com/JasperFx/lamar/blob/master/src/Lamar.Microsoft.DependencyInjection/LoggerInstance.cs#L35

We have a ILogger<T> decorator too, to capture scope before each log.

**Comment by jeremydmiller** [comment]
What you're trying to do might be better off w/ this: https://jasperfx.github.io/lamar/documentation/ioc/registration/policies/. You could remove the built in policies and add your own too for that matter. One way or another, everything goes into the ServiceCollection, and you can remove registrations from that too

**Comment by jeremydmiller** [comment]
The workaround for this issue came in through a PR to Lamar 1.2
