### ISSUE TITLE
Compilation failures due to incorrect generated code of DbContextPool

### ISSUE THREAD

**Issue by xczdbb** [JasperFx/lamar#87]
I think the error results from the quote `DbContextPool"1.Lease`.

Compilation failures!

CS1010: Newline in constant
CS1003: Syntax error, '>' expected
CS1514: { expected
CS1513: } expected
CS0116: A namespace cannot directly contain members such as fields or methods
CS1010: Newline in constant
CS1022: Type or namespace definition, or end-of-file expected
CS0116: A namespace cannot directly contain members such as fields or methods
CS1010: Newline in constant
CS1022: Type or namespace definition, or end-of-file expected
CS1022: Type or namespace definition, or end-of-file expected
CS0116: A namespace cannot directly contain members such as fields or methods
CS0116: A namespace cannot directly contain members such as fields or methods
CS1520: Method must have a return type
CS0305: Using the generic type 'DbContextPool<TContext>' requires 1 type arguments
CS0534: 'Microsoft_EntityFrameworkCore_Internal_DbContextPool_1_Lease_Zhiji_Contracts_Infrastructure_ContractContext__lease' does not implement inherited abstract member 'ScopedResolver<DbContextPool>.Build(Scope)'
CS0103: The name '_dbContextPool_of_ContractContext' does not exist in the current context
CS0122: 'ScopedResolver<DbContextPool>.ScopedResolver()' is inaccessible due to its protection level

Code:

```
using Microsoft.EntityFrameworkCore.Internal;
using System.Threading.Tasks;

namespace Jasper.Generated
{
    // START: Microsoft_EntityFrameworkCore_Internal_DbContextPool_1_Lease_Zhiji_Contracts_Infrastructure_ContractContext__lease
    public class Microsoft_EntityFrameworkCore_Internal_DbContextPool_1_Lease_Zhiji_Contracts_Infrastructure_ContractContext__lease : Lamar.IoC.Resolvers.ScopedResolver<Microsoft.EntityFrameworkCore.Internal.DbContextPool"1.Lease<Zhiji.Contracts.Infrastructure.ContractContext>>
    {
        private readonly Microsoft.EntityFrameworkCore.Internal.DbContextPool<Zhiji.Contracts.Infrastructure.ContractContext> _dbContextPool_of_ContractContext;

        public Microsoft_EntityFrameworkCore_Internal_DbContextPool_1_Lease_Zhiji_Contracts_Infrastructure_ContractContext__lease(Microsoft.EntityFrameworkCore.Internal.DbContextPool<Zhiji.Contracts.Infrastructure.ContractContext> dbContextPool_of_ContractContext)
        {
            _dbContextPool_of_ContractContext = dbContextPool_of_ContractContext;
        }



        public override Microsoft.EntityFrameworkCore.Internal.DbContextPool"1.Lease<Zhiji.Contracts.Infrastructure.ContractContext> Build(Lamar.IoC.Scope scope)
        {
            return new Microsoft.EntityFrameworkCore.Internal.DbContextPool"1.Lease<Zhiji.Contracts.Infrastructure.ContractContext>(_dbContextPool_of_ContractContext);
        }

    }

    // END: Microsoft_EntityFrameworkCore_Internal_DbContextPool_1_Lease_Zhiji_Contracts_Infrastructure_ContractContext__lease
    
    
}


```

My code uses `DbContextPool` like this:

        public void ConfigureEntityFramework(ServiceRegistry services)
        {
            services
                .AddEntityFrameworkSqlServer()
                .AddDbContextPool<ContractContext>(
                    opt => opt
                        .UseSqlServer(this.Configuration.GetConnectionString("Master"),
                            o => o.EnableRetryOnFailure()));
         }

            using (var scope = webHost.Services.CreateScope())
            {
                //the next line throws System.InvalidOperationException: Compilation failures!
                using (var context = scope.ServiceProvider.GetService<TContext>())
                {
                       //xxx
                }
            }

**Comment by Megasware128** [comment]
I did also walk into the same issue when using DbContext pool

**Comment by CodingGorilla** [comment]
I've run into this recently as well and I'm looking into it, the offending registration seems to be:
```
serviceCollection.AddScoped<TContextService>((Func<IServiceProvider, TContextService>) (sp => (TContextService) sp.GetService<DbContextPool<TContextImplementation>.Lease>().Context));
```

This is probably because when Lamar sees a registration for a particular type, it expects to construct that type and not execute a function.  As opposed to when it sees a registration for a `Func<T>` then it expects to run that function rather than construct `T`.

I'm still trying to figure out where exactly that decision is made, since this is a `ServiceDescriptor` that is "injected" into Lamar from Microsoft's DI system.  Maybe @jeremydmiller can point me in the right direction? 😄

**Comment by CodingGorilla** [comment]
Ahh, so I was mistaken, there is a nested class inside of `DbContextPool` called `Lease` and this is what it is attempting to instantiate.  So this seems to be another instance of the type name not being properly sanitized.  Still digging into why though.

**Comment by jeremydmiller** [comment]
Close by https://github.com/JasperFx/lamar/pull/88
