### ISSUE TITLE
Documentation Update

### ISSUE THREAD

**Issue by rdurham1007** [JasperFx/lamar#89]
Looks like the project was bumped to version 1.1.2 but the documentation hasn't been generated since 1.0 which was back in Jun. So currently the doc is missing updates from this commit made in July.

https://github.com/JasperFx/lamar/commit/47beb430a49bb4cba8a65340a6f76e949ec59022#diff-9b880b4fd9ad1e994f7ae51ddfc0be02

**Comment by jeremydmiller** [comment]
I haven't quite managed to publish the 2.0 nugets, but the documentation is updated. Now I'm out of sync the other way around:)
