### ISSUE TITLE
Allow Inject() to replace previous entries

### ISSUE THREAD

**Issue by seanterry** [JasperFx/lamar#93]
The Inject method only accepts the first injected instance, and subsequent calls throw an exception.

I would like to add an overload to optionally replace an existing injected entry when Inject is called, but would leave the existing implementation unchanged. Additionally, I'd like to see a non-generic overload of Inject. This would cover nearly all of my use cases for StructureMap's With method that are blocking my adoption of Lamar.

I'll attach a pull request for review, and thank you so much for sharing these projects with us.

**Comment by jeremydmiller** [comment]
Fixed by https://github.com/JasperFx/lamar/pull/94
