### ISSUE TITLE
DefaultConventionScanner will overwrite registrations added prior to Lamar's scanning

### ISSUE THREAD

**Issue by CodingGorilla** [JasperFx/lamar#97]
**Problem:**

In ASP.Net Core 2.1, the recommended way to use the `HttpClient` is to register and configure the client via the `IStartup.ConfigureServices()` method.  A registration might look like this:

```
public void ConfigureServices(IServiceCollection services)
{
  services.AddHttpClient<ISubscriptionsServiceClient, SubscriptionsServiceClient>()
      .ConfigureHttpClient((sp, client) =>
                 {
                   var baseUrl = sp.GetRequiredService<IOptions<MyOptions>>().Value.SubscriptionServiceUri;
                   client.BaseAddress = new Uri(baseUrl, UriKind.Absolute);
                 })
      .AddHttpMessageHandler<SystemServiceAuthorizationHandler>();
}
```

As this is added to the `ServiceCollection` first, a subsequent call to `ConfigureContainer()` which runs an assembly scan will cause this registration to be overwritten by the convention based auto-registration.  This **only applies** to registrations like this one which specify an interface to concrete registration (it's not required to register the HttpClient's with an interface, but it would be typical for facilitating unit tests).

**Proposed Soltuion**
Modify the `DefaultConventionScanner` with an option to skip existing registrations.  I know it's possible to create a custom convention scanner that will do this, but this seems like something that a lot of people in the ASP.Net core world are likely to run into.

The option would be off by default, so as to not change the current behavior.  When the scanner runs it when it discovered an interface as a candidate for registration, it would first check to see if that type has already been registered and skip the registration if it exists.

**Comment by xorets** [comment]
Could it also be related to this: https://github.com/JasperFx/lamar/issues/80?

**Comment by CodingGorilla** [comment]
@AndrewMayorov If you're doing type scanning, and Lamar is re-registering the logging classes by convention, then yea I could see that happening.  You could confirm this by using a different (or no) convention while scanning.

**Comment by jeremydmiller** [comment]
@AndrewMayorov I don't see how these two are related unless you were doing some type scanning that picked up logging registrations as well that overwrote what was in the default registrations

**Comment by jeremydmiller** [comment]
And ugh, it's harder than just doing that because in this case, the `ServiceRegistry` would not know anything about the existing ASP.Net Core registrations in a separate `ServiceCollection`.

**Comment by jeremydmiller** [comment]
@CodingGorilla So the old DefaultConventionScanner does *not* overwrite registrations if they exist with an exact match of service type & implementation type. That *particular* mechanism fools the default scanner because the AddHttpClient is using a lambda to build it, making the scanner think it's all different.

**Comment by CodingGorilla** [comment]
@jeremydmiller If I'm understanding what you're saying, you are right.  Instead of executing the `HttpClient` builder function, _and then_ building the registered implementation with the configured `HttpClient` injected, you just get a raw implentation class with a raw HttpClient.

The work around for this is to make sure that you call the `.AddHttpClient()` in your `ConfigureContainer()` after all the scanning is done.  But that's a bit inelegant (IMO).

**Comment by jeremydmiller** [comment]
@CodingGorilla Yep. Other workaround is to tell the type scanning to ignore anything that implements IHttpClient to sidestep the problem.

Am working up your suggestion right now though

**Comment by jeremydmiller** [comment]
@CodingGorilla Either way, this is gonna take some documentation work about using Lamar w/ ASP.Net Core. I'm not super thrilled w/ the ASP.Net Core internals on this one.

**Comment by CodingGorilla** [comment]
> Yep. Other workaround is to tell the type scanning to ignore anything that implements IHttpClient to sidestep the problem.

The actual implementation class does not implement IHttpClient, it takes an `HttpClient` as a constructor paramter.  So if I register:

```
services.AddHttpClient<ISubscriptionsServiceClient, SubscriptionsServiceClient>()
```

My `ISubscriptionServiceClient` is defined as:

```
    public interface ISubscriptionsServiceClient
    {
        Task<int?> GetAdditionalConcurrentLoginsForSubscriberAsync(string subscriberId);
    }
```

There's no indication of anything to do with `HttpClient`.

**Comment by jeremydmiller** [comment]
What does ISubscriptionsServiceClient and SubscriptionsServiceClient look like? Any kind of marker that would distinguish them to the Lamar type scanning?

Oh, and there's also [LamarIgnore] you could stick on the concrete class

**Comment by CodingGorilla** [comment]
There's nothing that makes them unique, unless you inspect the constructor parameters.  I knew about `[LamarIgnore]`, that also just seems inelegant to me.  As someone reading the code with no prior knowledge, I would see that at and assume that it is not being registered in the container at all.

I _thought_ my suggestion would be a fairly simple solution, but apparently not, so maybe we just have to live with the workarounds?

**Comment by jeremydmiller** [comment]
I'm not sure. Some of it depends on the greater ASP.Net Core mechanics. It doesn't work if the Lamar ServiceRegistry doesn't know about any previous registrations.  You can do a `new ServiceRegistry(IServiceCollection)`.

Another idea is to depend on calling AddLamar() to a ServiceCollection and eliminating `UseLamar` altogether, because that might actually work out ordering wise.

Another workaround is to do something in Lamar to "know" that the services discovered by the type scanning are a lower priority than other registrations when it decides on the default. That way sounds like madness if it doesn't work exactly right, but that's less expectations on the user and closer to how SM used to work.

StructureMap got around this by its differentiation between `Use()` as the default and `Add()` as just an additional one, but I dropped that in Lamar because there's no semantic equivalent in ASP.Net Core world

**Comment by CodingGorilla** [comment]
For my 2 pennies worth, I like the idea of a `.AddLamar()`, since it sticks with established patterns.  It also would eliminate the need for the `ConfigureContainer()` method in your Startup class, as we could potentially pass in a delegate that does the equivalent configuration right there in `ConfigureServices()`.

Would this actually solve the problem though, wouldn't we have the same problem unless the `.AddLamar()` is done as the first thing in `ConfigureServices()`.

The other suggestion, kind of scares me; it seems like that could cause all kinds of chaos and confusion. 😄

**Comment by jeremydmiller** [comment]
You would be dependent upon doing the `AddLamar()` in the right order inside of the Startup.ConfigureServices(), but that doesn't sound too bad. Regardless, I think there needs to be more content in the documentation for Lamar + ASP.Net Core. 

And check the PR that closes this issue too.
